const dyCards = {
  insanhak:[
    {s:"İnsan Hakları Evrensel Beyannamesi devletler için hukuken bağlayıcıdır.",ans:false,exp:"İHEB bağlayıcı değil, tavsiye niteliğindedir. Bağlayıcı olan AİHS gibi uluslararası sözleşmelerdir."},
    {s:"AİHS'te düzenlenen işkence yasağı hiçbir koşulda askıya alınamaz.",ans:true,exp:"AİHS m.3 mutlak bir haktır; savaş ya da olağanüstü hal dahil hiçbir koşulda askıya alınamaz."},
    {s:"Türkiye, AİHM'e bireysel başvuru hakkını 1999 yılında tanımıştır.",ans:false,exp:"Türkiye bireysel başvuru hakkını 28 Ocak 1987'de tanımıştır."},
    {s:"Adil yargılanma hakkı kapsamında masumiyet karinesi yer almaktadır.",ans:true,exp:"AİHS m.6/2: Bir suç ile itham edilen herkes, suçluluğu yasal olarak sabit oluncaya kadar masum sayılır."},
    {s:"BM 1945 yılında San Francisco'da kurulmuştur.",ans:true,exp:"BM Şartı 26 Haziran 1945'te San Francisco'da imzalanmış, 24 Ekim 1945'te yürürlüğe girmiştir."},
    {s:"İHEB 25 maddeden oluşmaktadır.",ans:false,exp:"İHEB 30 maddeden oluşmaktadır. 10 Aralık 1948'de BM Genel Kurulu'nca kabul edilmiştir."},
    {s:"Avrupa İnsan Hakları Mahkemesi bir Avrupa Birliği kurumudur.",ans:false,exp:"AİHM, AB değil Avrupa Konseyi bünyesindedir. Avrupa Konseyi ile Avrupa Birliği farklı kuruluşlardır."},
    {s:"Kölelik yasağı olağanüstü hallerde geçici olarak askıya alınabilir.",ans:false,exp:"Kölelik yasağı (AİHS m.4) mutlak bir haktır; hiçbir koşulda askıya alınamaz."},
    {s:"AİHS 1950 yılında imzalanmıştır.",ans:true,exp:"AİHS 4 Kasım 1950'de Roma'da imzalanmış, 3 Eylül 1953'te yürürlüğe girmiştir."},
    {s:"Avrupa Konseyi'nin merkezi Brüksel'dedir.",ans:false,exp:"Avrupa Konseyi'nin merkezi Strazburg'dadır. Brüksel ise AB kurumlarının bulunduğu şehirdir."},
    {s:"AİHS'te 'ifade özgürlüğü' 10. maddede düzenlenmektedir.",ans:true,exp:"AİHS m.10 ifade özgürlüğünü güvence altına alır; ancak ulusal güvenlik, başkalarının hakları gibi gerekçelerle sınırlandırılabilir."},
    {s:"Uluslararası Ceza Mahkemesi (UCM) Lahey'de bulunmaktadır.",ans:true,exp:"UCM 2002'de Roma Statüsü'yle kurulmuş ve Lahey, Hollanda'da faaliyet göstermektedir."},
    {s:"AİHS'teki hakların tamamı mutlak olup hiçbir koşulda sınırlandırılamaz.",ans:false,exp:"AİHS'teki hakların yalnızca bir kısmı mutlaktır (işkence yasağı, kölelik yasağı gibi). Büyük çoğunluğu ulusal güvenlik, kamu düzeni gibi meşru amaçlarla sınırlandırılabilir."},
    {s:"Çocuk Hakları Sözleşmesi 1989 yılında BM tarafından kabul edilmiştir.",ans:true,exp:"BM Çocuk Hakları Sözleşmesi 20 Kasım 1989'da kabul edilmiş; Türkiye 1995'te onaylamıştır."},
    {s:"AİHM kararları Türkiye için bağlayıcı değildir.",ans:false,exp:"Türkiye AİHS'i onaylamış ve AİHM'in yargı yetkisini kabul etmiştir; mahkeme kararları bağlayıcıdır."},
    {s:"İkiz Sözleşmeler 1966 yılında BM tarafından kabul edilmiştir.",ans:true,exp:"Medeni ve Siyasi Haklar ile Ekonomik, Sosyal ve Kültürel Haklar Uluslararası Sözleşmeleri 16 Aralık 1966'da kabul edilmiştir."},
    {s:"Kişi özgürlüğü ve güvenliği hakkı AİHS'in 5. maddesinde güvence altına alınmıştır.",ans:true,exp:"AİHS m.5 kişi özgürlüğü ve güvenliği hakkını düzenler; keyfi tutuklamayı yasaklar ve hâkim önüne çıkarılma hakkını güvence altına alır."},
    {s:"Avrupa İnsan Hakları Komisyonu bugün hâlâ aktif olarak çalışmaktadır.",ans:false,exp:"Eski Avrupa İnsan Hakları Komisyonu, 1998'de AİHM'in yeniden yapılandırılmasıyla kaldırılmıştır."},
    {s:"BM Güvenlik Konseyi ağır insan hakları ihlalleri nedeniyle yaptırım uygulayabilir.",ans:true,exp:"BM Güvenlik Konseyi ağır insan hakları ihlallerini uluslararası barış ve güvenliğe tehdit sayarak yaptırım kararı alabilir."},
    {s:"AİHS'e Ek 1 No'lu Protokol mülkiyet hakkını güvence altına almaktadır.",ans:true,exp:"AİHS'e Ek 1 No'lu Protokol m.1: Her gerçek ve tüzel kişinin mülkiyetini barışçıl biçimde kullanma hakkı güvence altındadır."},
  ],
  anayasa:[
    {s:"Türkiye Cumhuriyeti Anayasası'na göre Cumhuriyet, oy çokluğuyla değiştirilebilir.",ans:false,exp:"Anayasa m.4: Cumhuriyetin niteliklerine ilişkin maddeler değiştirilemez; teklif dahi edilemez."},
    {s:"TBMM 600 milletvekilinden oluşmaktadır.",ans:true,exp:"2017 anayasa değişikliğiyle milletvekili sayısı 600'e çıkarılmış, ilk kez 2018 seçimlerinde uygulanmıştır."},
    {s:"Anayasa değişikliği için salt çoğunluk (301 oy) yeterlidir.",ans:false,exp:"Anayasa m.175: Değişiklik teklifi en az beşte üç (360) oyla kabul edilebilir."},
    {s:"Anayasa Mahkemesi'ne bireysel başvuru 2012'den itibaren mümkündür.",ans:true,exp:"2010 değişikliğiyle düzenlenen bireysel başvuru, 23 Eylül 2012'den itibaren uygulamaya girmiştir."},
    {s:"Temel haklar olağanüstü hallerde tamamen kaldırılabilir.",ans:false,exp:"Anayasa m.15: Temel haklar kısmen askıya alınabilir; ancak işkence yasağı gibi mutlak haklar kısıtlanamaz."},
    {s:"Türkiye Cumhurbaşkanı halk tarafından doğrudan seçilmektedir.",ans:true,exp:"2017 anayasa değişikliğiyle Cumhurbaşkanı, doğrudan halk tarafından 5 yıllık süre için seçilmektedir."},
    {s:"Anayasa m.2'deki devletin temel nitelikleri yüzde elli artı bir oyla değiştirilebilir.",ans:false,exp:"Anayasa m.4 gereği m.2 değiştirilemez, değiştirilmesi teklif dahi edilemez."},
    {s:"Türkiye Cumhuriyeti'nin başkenti İstanbul'dur.",ans:false,exp:"Anayasa m.3: Türkiye Cumhuriyeti'nin başkenti Ankara'dır. Bu hüküm değiştirilemez."},
    {s:"Anayasa Mahkemesi üyeleri 12 yıl süreyle görev yapar.",ans:true,exp:"AYM üyeleri Cumhurbaşkanı tarafından atanır ve 12 yıllık görev süresi sonunda yeniden atanamazlar."},
    {s:"TBMM milletvekilleri 4 yıllık dönem için seçilir.",ans:false,exp:"Milletvekilleri 5 yıllık dönem için seçilir. 2017 değişikliğiyle 4 yıldan 5 yıla çıkarılmıştır."},
    {s:"Cumhurbaşkanı en fazla iki dönem görev yapabilir.",ans:true,exp:"2017 anayasa değişikliğine göre Cumhurbaşkanı en fazla iki 5 yıllık dönem görev yapabilir."},
    {s:"Türkiye'de olağanüstü hal en fazla 2 ay sürebilir.",ans:false,exp:"Anayasa m.119: Olağanüstü hal en fazla 6 aydır; TBMM gerekli görürse uzatabilir."},
    {s:"Milletvekili seçilebilmek için en az üniversite mezunu olmak gerekir.",ans:false,exp:"Anayasa m.76: Milletvekili seçilebilmek için ilkokul mezunu olmak yeterlidir. Üniversite mezuniyeti Cumhurbaşkanı için şarttır."},
    {s:"Anayasa m.3'e göre Türkiye'nin millî marşı İstiklal Marşı'dır.",ans:true,exp:"Anayasa m.3: Türkiye Cumhuriyeti'nin dili Türkçe, bayrağı Kırmızı-Beyaz, millî marşı İstiklal Marşı, başkenti Ankara'dır."},
    {s:"Türkiye Cumhuriyeti Anayasası 1982 yılında yürürlüğe girmiştir.",ans:true,exp:"1982 Anayasası 7 Kasım 1982'de referandumla kabul edilerek yürürlüğe girmiştir."},
    {s:"Anayasa Mahkemesi 12 asıl üyeden oluşmaktadır.",ans:true,exp:"Anayasa m.146: Anayasa Mahkemesi 12 asıl üyeden oluşur; üyeleri Cumhurbaşkanı çeşitli kurumların gösterdiği adaylar arasından atar."},
    {s:"Olağan Cumhurbaşkanlığı kararnamesiyle temel haklar kısıtlanabilir.",ans:false,exp:"Anayasa m.13: Temel haklar yalnızca kanunla sınırlandırılabilir. Cumhurbaşkanlığı kararnamesi temel hakları doğrudan düzenleyemez."},
    {s:"TBMM'nin aynı konuda kanun çıkarması halinde Cumhurbaşkanlığı kararnamesi geçersiz olur.",ans:true,exp:"Anayasa m.104: TBMM'nin kanun düzenlediği bir alanda çıkarılan Cumhurbaşkanlığı kararnamesi hükmü geçerliliğini yitirir."},
    {s:"Anayasa'nın 1. maddesinde devlet şeklinin Cumhuriyet olduğu belirtilmektedir.",ans:true,exp:"Anayasa m.1: 'Türkiye Devleti bir Cumhuriyettir.' Bu madde değiştirilemez ve değiştirilmesi teklif dahi edilemez."},
    {s:"Anayasa'ya göre temel haklar yalnızca kanunla sınırlandırılabilir.",ans:true,exp:"Anayasa m.13: Temel hak ve özgürlükler özlerine dokunulmaksızın yalnızca Anayasa'nın ilgili maddelerindeki sebeplere bağlı olarak ve ancak kanunla sınırlanabilir."},
  ],
  inkılap:[
    {s:"Türkiye Cumhuriyeti 29 Ekim 1923'te ilan edilmiştir.",ans:true,exp:"Türkiye Cumhuriyeti 29 Ekim 1923'te ilan edilmiş, Mustafa Kemal Atatürk ilk Cumhurbaşkanı seçilmiştir."},
    {s:"Halifelik 1922 yılında kaldırılmıştır.",ans:false,exp:"Halifelik 3 Mart 1924'te kaldırılmıştır. 1922'de saltanat kaldırılmıştır."},
    {s:"Lozan Antlaşması 24 Temmuz 1923'te imzalanmıştır.",ans:true,exp:"Lozan Antlaşması 24 Temmuz 1923'te imzalanmış; Türkiye'nin bağımsızlığı ve sınırları uluslararası alanda tanınmıştır."},
    {s:"Harf İnkılabı 1925 yılında gerçekleşmiştir.",ans:false,exp:"Harf İnkılabı 1 Kasım 1928'de gerçekleşmiştir. Arap alfabesinden Latin alfabesine geçilmiştir."},
    {s:"Türk kadınlarına milletvekili seçme ve seçilme hakkı 1934'te verilmiştir.",ans:true,exp:"5 Aralık 1934'te Türk kadınları milletvekili seçme ve seçilme hakkını kazanmıştır."},
    {s:"Atatürk'ün Altı İlkesi 1937 yılında Anayasa'ya girmiştir.",ans:true,exp:"Cumhuriyetçilik, Milliyetçilik, Halkçılık, Devletçilik, Laiklik, Devrimcilik ilkeleri 1937'de Anayasa'ya eklenmiştir."},
    {s:"TBMM 23 Nisan 1919'da kurulmuştur.",ans:false,exp:"TBMM 23 Nisan 1920'de Ankara'da açılmıştır."},
    {s:"Türk Medeni Kanunu İsviçre Medeni Kanunu esas alınarak hazırlanmıştır.",ans:true,exp:"1926'da yürürlüğe giren Türk Medeni Kanunu, İsviçre Medeni Kanunu'ndan uyarlanmıştır."},
    {s:"Mondros Mütarekesi 1919 yılında imzalanmıştır.",ans:false,exp:"Mondros Mütarekesi 30 Ekim 1918'de imzalanmıştır."},
    {s:"İstiklal Marşı Mehmet Akif Ersoy tarafından yazılmıştır.",ans:true,exp:"İstiklal Marşı Mehmet Akif Ersoy tarafından kaleme alınmış ve 12 Mart 1921'de TBMM tarafından kabul edilmiştir."},
  ,
    {s:"Lozan Barış Antlaşması 24 Temmuz 1923'te imzalanmıştır.",ans:true,exp:"Doğru. Lozan 24 Temmuz 1923'te imzalandı ve Türkiye Cumhuriyeti'nin uluslararası tanınmasını sağladı."},
    {s:"Atatürk'ün 6 ilkesinden biri 'sosyalizm'dir.",ans:false,exp:"Yanlış. Altı Ok: Cumhuriyetçilik, Milliyetçilik, Halkçılık, Devletçilik, Laiklik, İnkılâpçılık. Sosyalizm bu ilkeler arasında değildir."},
    {s:"Harf Devrimi 1928'de gerçekleşmiş ve Latin alfabesi benimsenmiştir.",ans:true,exp:"Doğru. 1 Kasım 1928'de Arap harfleri kaldırılarak Latin esaslı Türk alfabesi kabul edildi."},
    {s:"Türk Medeni Kanunu Fransız Medeni Kanunu'ndan uyarlanmıştır.",ans:false,exp:"Yanlış. 1926 tarihli Türk Medeni Kanunu İsviçre Medeni Kanunu esas alınarak hazırlandı."},
    {s:"Kadınlara milletvekili seçme ve seçilme hakkı 1934'te tanınmıştır.",ans:true,exp:"Doğru. 5 Aralık 1934. Belediye seçimlerinde oy hakkı ise 1930'da verilmişti."},
    {s:"Sivas Kongresi, Erzurum Kongresi'nden önce toplandı.",ans:false,exp:"Erzurum Kongresi 23 Temmuz–7 Ağustos 1919 tarihleri arasında toplandı; Sivas Kongresi ise 4–11 Eylül 1919'da gerçekleşti."},
    {s:"Misak-ı Millî kararları son Osmanlı Mebusan Meclisi tarafından alınmıştır.",ans:true,exp:"Misak-ı Millî 28 Ocak 1920'de İstanbul'daki son Osmanlı Mebusan Meclisi tarafından kabul edilmiştir."},
    {s:"Türk-Yunan Nüfus Mübadelesi din esasına göre düzenlenmiştir.",ans:true,exp:"1923 Lozan Antlaşması kapsamındaki nüfus mübadelesi milliyet değil din esas alınarak yapılmıştır. Karamanlılar ve İstanbul Rumları kapsam dışı tutulmuştur."},
    {s:"Atatürk'ün 'Nutuk'u üç gün süren bir konuşmadır.",ans:false,exp:"Nutuk 15–20 Ekim 1927 tarihleri arasında 6 gün sürmüştür (yaklaşık 36 saat). 'Üç gün' ifadesi yanlıştır."},
    {s:"Tevhid-i Tedrisat Kanunu 1924 yılında çıkarılarak eğitimde birlik sağlanmıştır.",ans:true,exp:"3 Mart 1924 tarihli Tevhid-i Tedrisat Kanunu tüm okulları Millî Eğitim Bakanlığı'na bağlamış, eğitimde laikleşmenin temelini atmıştır."},
  ],
  polismev:[
    {s:"Polis, makul şüphe olmaksızın herkesi durdurabilir.",ans:false,exp:"PVSK m.4/A: Durdurma yetkisi makul ve somut olgulara dayanan şüphe varlığını gerektirir."},
    {s:"Gözaltı süresi kural olarak 24 saati geçemez.",ans:true,exp:"CMK m.91: Yakalanan kişi en geç 24 saat içinde hâkim önüne çıkarılmalıdır."},
    {s:"Adli kolluğun amiri Emniyet Müdürlüğü'dür.",ans:false,exp:"CMK m.161: Adli görevlerde kolluk, Cumhuriyet Savcısı'na tabidir."},
    {s:"Konut araması kural olarak hâkim kararı gerektirir.",ans:true,exp:"CMK m.119: Konut araması kural olarak hâkim kararıyla yapılır."},
    {s:"Kolluk, silah kullanmadan önce sözlü uyarı yapmak zorunda değildir.",ans:false,exp:"PVSK m.16: Silah kullanmadan önce 'dur' komutu verilmeli ve gerekirse uyarı ateşi açılmalıdır."},
    {s:"Toplantı ve gösteri yürüyüşleri için 48 saat önceden bildirim yapılmalıdır.",ans:true,exp:"2911 sayılı Kanun: En az 48 saat önce yazılı bildirim yapılmalıdır."},
    {s:"Vali, il sınırları içindeki hem polis hem jandarmanın en büyük amiridir.",ans:true,exp:"5442 sayılı İl İdaresi Kanunu: Vali, il sınırları içindeki tüm kolluk kuvvetlerinin en büyük amiridir."},
    {s:"Kimlik tespiti amacıyla kişi 2 saate kadar nezarette tutulabilir.",ans:false,exp:"PVSK m.4/A: Kimlik tespiti için azami süre 4 saattir."},
    {s:"Tutuklama kararı Cumhuriyet Savcısı tarafından verilebilir.",ans:false,exp:"Tutuklama kararı yalnızca sulh ceza hâkimi tarafından verilebilir."},
    {s:"Önleme araması suç işlenmeden önce yapılabilir.",ans:true,exp:"Önleme araması idari amaçlıdır; suç işlenmesini önlemek için mülki amir kararıyla yapılabilir."},
  ,
    {s:"PVSK'ya göre durdurma süresi 30 dakikayı geçemez.",ans:true,exp:"Doğru. PVSK m.4/A: Durdurma süresi en fazla 30 dakikadır. Kimlik tespiti için götürmede süre en fazla 4 saattir."},
    {s:"Polis, makul şüphe olmaksızın istediği kişiyi durdurabilir.",ans:false,exp:"Yanlış. PVSK m.4/A: Durdurma yetkisi ancak makul şüphe bulunması halinde kullanılabilir. Keyfi durdurma hukuka aykırıdır."},
    {s:"Silah kullanmadan önce dur emri ve uyarı ateşi zorunludur.",ans:true,exp:"Doğru. PVSK m.16: Önce dur emri, ardından uyarı ateşi, son olarak etkisiz kılmaya yönelik ateş — bu sıraya uymak zorunludur."},
    {s:"Emniyet Genel Müdürlüğü İçişleri Bakanlığı'na bağlıdır.",ans:true,exp:"Doğru. Emniyet Genel Müdürlüğü İçişleri Bakanlığı bünyesinde yer alır. Ülkenin genel emniyet işlerinden İçişleri Bakanı sorumludur."},
    {s:"Toplantı ve gösteri yürüyüşleri için önceden izin alınması gerekir.",ans:false,exp:"Yanlış. Anayasa m.34 ve 2911 sayılı Kanun: İzin değil bildirim usulü geçerlidir. Önceden izin şartı bu hakkı ortadan kaldırır."},
    {s:"Jandarma, kırsal alanlarda hem idari hem adli kolluk görevini üstlenir.",ans:true,exp:"Jandarma şehir ve kasabalar dışındaki yerlerde idari ve adli kolluk görevini birlikte yürütür."},
    {s:"Polis memurlarının grev hakkı Anayasa ile güvence altına alınmıştır.",ans:false,exp:"Kamu görevlilerinin grev hakkı anayasal düzeyde kısıtlanmıştır; polis memurları grev yapamaz."},
    {s:"Emniyet teşkilatının en üst amiri Emniyet Genel Müdürü'dür.",ans:true,exp:"Emniyet Genel Müdürü, İçişleri Bakanlığı'na bağlı olarak ülke genelindeki emniyet teşkilatının başıdır."},
    {s:"Suçüstü hâlinde kolluk kuvveti ruhsatsız silah bulunduran kişiyi gözaltına alabilir.",ans:true,exp:"PVSK: Suçüstü hâlinde kolluk kuvveti kişiyi gözaltına alabilir; ruhsatsız silah bulundurma bu kapsamdadır."},
    {s:"Polisin silah kullanma yetkisi orantılılık ilkesiyle sınırlıdır.",ans:true,exp:"PVSK m.16: Silah kullanma yetkisi zorunluluk, son çare olma ve orantılılık ilkelerine tabi olup bu ilkelere aykırı kullanım hukuka aykırıdır."},
  ],
  idare:[
    {s:"İdare mahkemelerinde dava açma süresi kural olarak 60 gündür.",ans:true,exp:"İYUK m.7: İdari dava açma süresi tebliğden itibaren 60 gündür. Vergi mahkemelerinde 30 gün."},
    {s:"Danıştay, idari yargının en üst mahkemesidir.",ans:true,exp:"Danıştay idari yargı düzeninin en üst mahkemesi ve temyiz merciidir."},
    {s:"İdari para cezaları adli sicile işlenir.",ans:false,exp:"İdari para cezaları idari yaptırım niteliğindedir; adli sicile işlenmez."},
    {s:"Takdir yetkisi idarenin sınırsız karar alma özgürlüğü anlamına gelir.",ans:false,exp:"Takdir yetkisi hukuk sınırları içinde kullanılmalıdır; keyfi karar alma yasaktır."},
    {s:"Tam yargı davasında hem iptal hem tazminat talep edilebilir.",ans:true,exp:"Tam yargı davasında hem işlemin iptali hem de uğranılan zararın tazmini birlikte istenebilir."},
    {s:"Ombudsman (KDK) kararları idare için bağlayıcıdır.",ans:false,exp:"KDK kararları bağlayıcı değil, tavsiye niteliğindedir."},
    {s:"Yetki genişliği ilkesi yerinden yönetimin bir türüdür.",ans:false,exp:"Yetki genişliği merkezden yönetim içinde yer alır; taşra amirine merkez adına karar alma yetkisi tanınmasıdır."},
    {s:"İdari işlemin amaç unsurundaki sakatlık 'yetki saptırması' olarak adlandırılır.",ans:true,exp:"Amaç unsurundaki sakatlık, yetkinin öngörülen amaç dışında kullanılması ve 'yetki saptırması' olarak adlandırılır."},
    {s:"Belediyeler merkezi yönetimin bir parçasıdır.",ans:false,exp:"Belediyeler ayrı tüzel kişiliğe sahip yerel yönetim birimleri; yerinden yönetim kuruluşudur."},
    {s:"İptal davası açılabilmesi için idari başvuru yolu zorunlu olarak tüketilmek zorundadır.",ans:false,exp:"Kural olarak zorunlu değildir; ancak bazı kanunlar zorunlu idari başvuru öngörebilir."},
    {s:"İdari işlemler kural olarak her zaman yazılı yapılmak zorundadır.",ans:false,exp:"İdari işlemlerin şekli kanunla belirlenir; bazı işlemler sözlü ya da zımni biçimde de tesis edilebilir."},
    {s:"Devlet memurlarının haksız eylemleri idarenin tazminat sorumluluğunu doğurabilir.",ans:true,exp:"Hizmet kusuru veya kusursuz sorumluluk ilkeleri çerçevesinde memurların eylemlerinden doğan zararlar idareye yükletilebilir."},
    {s:"Vergi uyuşmazlıkları adli yargıda çözümlenir.",ans:false,exp:"Vergi uyuşmazlıkları, idari yargı düzeni içindeki vergi mahkemelerinde çözümlenir."},
    {s:"İYUK'a göre vergi mahkemelerinde dava açma süresi 30 gündür.",ans:true,exp:"İYUK m.7: İdare mahkemelerinde dava açma süresi 60 gün; vergi mahkemelerinde ise 30 gündür."},
    {s:"Yargı, idarenin takdir yetkisinin yerindeliğini de denetleyebilir.",ans:false,exp:"Yargı idarenin takdir yetkisinin yalnızca hukuka uygunluğunu denetler; yerindeliği denetleyemez."},
    {s:"Kamu hizmetleri özel kişilerce de yürütülebilir.",ans:true,exp:"Kamu hizmetleri devlet, yerel yönetimler ya da imtiyaz/ruhsat gibi usullerle özel kişi ve kuruluşlara devredilebilir."},
    {s:"Mahalli idareler halk tarafından seçilen organlarla yönetilir.",ans:true,exp:"Anayasa m.127: Belediye, il özel idaresi ve köy yönetimleri seçimle göreve gelen organlar tarafından yönetilir."},
    {s:"İdarenin her türlü eylem ve işlemine karşı yargı yolu açıktır.",ans:true,exp:"Anayasa m.125: İdarenin her türlü eylem ve işlemi yargısal denetime tabidir; bu güvence anayasal düzeyde koruma altındadır."},
    {s:"İdari yaptırım olarak hapis cezası idare tarafından verilebilir.",ans:false,exp:"Anayasa m.38: İdare kişi hürriyetini kısıtlayan yaptırım uygulayamaz; idari para cezası verebilir ancak özgürlüğü kısıtlayıcı ceza veremez."},
    {s:"İdari sözleşmeler özel hukuk sözleşmelerinden daha geniş idare yetkisi tanır.",ans:true,exp:"İdari sözleşmelerde idare, kamu yararı gereği tek taraflı değişiklik ve fesih gibi ayrıcalıklı yetkiler kullanabilir; bu durum özel hukuk sözleşmelerinden temel farkı oluşturur."},
  ],
  gelkul:[
    {s:"Türkiye Cumhuriyeti 29 Ekim 1923'te ilan edilmiştir.",ans:true,exp:"Doğru. Türkiye Cumhuriyeti, Mustafa Kemal önderliğinde 29 Ekim 1923'te ilan edilmiştir."},
    {s:"Ankara, Türkiye'nin en kalabalık ilidir.",ans:false,exp:"Yanlış. En kalabalık il yaklaşık 15+ milyon nüfusla İstanbul'dur. Ankara nüfus bakımından ikinci sıradadır."},
    {s:"Kızılırmak, Türkiye'nin tamamen sınırları içinde akan en uzun nehridir.",ans:true,exp:"Doğru. Kızılırmak ~1355 km ile Türkiye sınırları içinde tamamen akan en uzun nehirdir. Karadeniz'e dökülür."},
    {s:"Türkiye 81 ilden oluşmaktadır.",ans:true,exp:"Doğru. Türkiye'de 81 il bulunmaktadır. Son eklenen il 1999'da Düzce'dir."},
    {s:"Türkiye'nin topraklarının büyük çoğunluğu Avrupa kıtasında yer alır.",ans:false,exp:"Yanlış. Türkiye topraklarının ~%97'si Anadolu (Asya), ~%3'ü Trakya (Avrupa) kıtasındadır."},
    {s:"Türkiye'de zorunlu eğitim süresi 12 yıldır.",ans:true,exp:"Doğru. 2012'de 4+4+4 sistemiyle zorunlu eğitim 8 yıldan 12 yıla çıkarıldı."},
    {s:"Türkiye yüzölçümü bakımından dünyanın en büyük 10 ülkesi arasındadır.",ans:false,exp:"Yanlış. Türkiye ~783.000 km² ile yaklaşık 36. büyük ülkedir; ilk 10 arasında değildir."},
    {s:"INTERPOL'ün merkezi Lyon, Fransa'dadır.",ans:true,exp:"Doğru. Uluslararası Kriminal Polis Örgütü INTERPOL'ün genel merkezi Lyon, Fransa'dadır."},
    {s:"Türkiye Cumhuriyeti Merkez Bankası İstanbul'da bulunmaktadır.",ans:false,exp:"Yanlış. Türkiye Cumhuriyet Merkez Bankası Ankara'da bulunmaktadır. 1930 yılında kurulmuştur."},
    {s:"Türkiye hem seçme hem milletvekili seçilme yaşı 18'dir.",ans:true,exp:"Doğru. 2017 anayasa değişikliğiyle her ikisi de 18 yaşına indirildi."},
    {s:"Türkiye G20 ülkeleri arasında yer almaktadır.",ans:true,exp:"Türkiye G20 üyesi olup dünyanın önde gelen ekonomileri arasında kabul edilmektedir."},
    {s:"Türkiye Boğazları Montrö Sözleşmesi ile düzenlenmektedir.",ans:true,exp:"1936 Montrö Sözleşmesi İstanbul Boğazı ve Çanakkale Boğazı'nın statüsünü belirlemektedir."},
    {s:"Türkiye'nin en yüksek dağı 5137 m ile Ağrı Dağı'dır.",ans:true,exp:"Ağrı Dağı 5137 m ile Türkiye'nin en yüksek zirvesidir; Doğu Anadolu'da yer alır."},
    {s:"Sosyal Güvenlik Kurumu (SGK) SSK, Bağ-Kur ve Emekli Sandığı birleştirilerek oluşturulmuştur.",ans:true,exp:"SGK 2006 yılında bu üç kurumun birleştirilmesiyle kurulmuş; emeklilik ve sosyal güvenlik işlemlerini yürütmektedir."},
    {s:"Türkiye OECD'nin kurucu üyelerinden biridir.",ans:true,exp:"OECD 1961'de kurulmuştur. Türkiye kurucu üyeler arasında yer alır."},
    {s:"Türkiye'nin para birimi Türk Lirası'dır.",ans:true,exp:"Türk Lirası Türkiye'nin resmi para birimidir; ISO kodu TRY'dir."},
    {s:"Atatürk 10 Kasım 1938'de vefat etmiştir.",ans:true,exp:"Mustafa Kemal Atatürk 10 Kasım 1938'de İstanbul Dolmabahçe Sarayı'nda hayatını kaybetmiştir."},
    {s:"Anadolu Ajansı Türkiye'nin ulusal haber ajansıdır.",ans:true,exp:"Anadolu Ajansı 6 Nisan 1920'de Mustafa Kemal tarafından kurulmuş; Türkiye'nin ulusal haber ajansı olarak görev yapmaktadır."},
    {s:"Türkiye'nin yüzölçümü yaklaşık 783.000 km²'dir.",ans:true,exp:"Türkiye'nin yüzölçümü yaklaşık 783.562 km²'dir; bu büyüklükle dünyada yaklaşık 36. sıradadır."},
    {s:"Türkiye Cumhuriyeti Merkez Bankası Ankara'da bulunmaktadır.",ans:true,exp:"Türkiye Cumhuriyet Merkez Bankası (TCMB) Ankara'da bulunmaktadır; 1930 yılında kurulmuştur."},
  ],
  guncel:[
    {s:"Türkiye NATO'nun kurucu üyeleri arasında yer almaktadır.",ans:false,exp:"NATO 4 Nisan 1949'da kurulmuştur. Türkiye 18 Şubat 1952'de katılmıştır; kurucu üye değildir."},
    {s:"Türkiye Cumhuriyeti 2023 yılında 100. kuruluş yılını kutlamıştır.",ans:true,exp:"Türkiye Cumhuriyeti 29 Ekim 2023'te 100. kuruluş yıl dönümünü kutlamıştır."},
    {s:"BM Güvenlik Konseyi'nin 5 daimi üyesi veto hakkına sahiptir.",ans:true,exp:"ABD, Rusya, Çin, Fransa ve Birleşik Krallık (P5) veto hakkına sahiptir."},
    {s:"Türkiye Avrupa Birliği'nin tam üyesidir.",ans:false,exp:"Türkiye AB üyesi değildir. Müzakereler başlamış fakat fiilen askıya alınmıştır."},
    {s:"Türkiye 81 ilden oluşmaktadır.",ans:true,exp:"Türkiye 81 ilden oluşmaktadır. Yüzölçümü yaklaşık 783.562 km²'dir."},
    {s:"Dünya İnsan Hakları Günü her yıl 10 Aralık'ta kutlanmaktadır.",ans:true,exp:"10 Aralık, İHEB'in 1948'de ilan edildiği gündür."},
    {s:"Avrupa Konseyi 1949'da kurulmuş ve Türkiye kurucu üyeler arasındadır.",ans:true,exp:"Avrupa Konseyi 5 Mayıs 1949'da kurulmuştur. Türkiye kurucu üyeler arasında yer almaktadır."},
    {s:"Türkiye, NATO'da kara kuvvetleri büyüklüğü bakımından birinci sıradadır.",ans:false,exp:"Türkiye NATO'da ABD'den sonra kara kuvvetleri büyüklüğünde ikinci sıradadır."},
    {s:"Türkiye'nin başkenti İstanbul'dur.",ans:false,exp:"Türkiye'nin başkenti 13 Ekim 1923'ten bu yana Ankara'dır."},
    {s:"BM 193 üye devletten oluşmaktadır.",ans:true,exp:"2011'de Güney Sudan'ın katılımıyla BM 193 üye devlete ulaşmıştır."},
  ,
    {s:"Türkiye NATO'nun kurucu üyeleri arasında yer almaktadır.",ans:false,exp:"Yanlış. NATO 1949'da kuruldu; Türkiye 1952'de Yunanistan ile birlikte katıldı. Kurucu üye değildir."},
    {s:"Türkiye'de 81 il bulunmaktadır.",ans:true,exp:"Doğru. Türkiye'de 81 il vardır. Son eklenen il 1999'da Düzce'dir."},
    {s:"BM Güvenlik Konseyi'nin 5 daimi üyesinden biri Almanya'dır.",ans:false,exp:"Yanlış. 5 daimi üye (P5): ABD, İngiltere, Fransa, Rusya ve Çin. Almanya daimi üye değildir."},
    {s:"AYM'ye bireysel başvuru hakkı 2012'de uygulamaya girmiştir.",ans:true,exp:"Doğru. 23 Eylül 2012'den itibaren bireysel başvuru hakkı kullanılabilmektedir. 2010 anayasa referandumuyla getirildi."},
    {s:"Kızılırmak Türkiye'nin tamamen kendi sınırları içinde akan en uzun nehridir.",ans:true,exp:"Doğru. ~1355 km ile Türkiye'nin en uzun iç nehridir. Fırat daha uzun ancak Suriye ve Irak'a da uzanır."},
    {s:"Avrupa Birliği merkezi Strazburg'da bulunmaktadır.",ans:false,exp:"AB'nin temel kurumları Brüksel ve Lüksemburg'dadır. Strazburg ise Avrupa Konseyi ve Avrupa Parlamentosu'nun bulunduğu şehirdir."},
    {s:"Türkiye Dünya Ticaret Örgütü'nün (DTÖ) üyesidir.",ans:true,exp:"Türkiye 1995'ten bu yana DTÖ üyesidir."},
    {s:"BM'nin altı resmi dilinden biri Türkçe'dir.",ans:false,exp:"BM'nin resmi dilleri Arapça, Çince, İngilizce, Fransızca, Rusça ve İspanyolca'dır. Türkçe bu diller arasında yer almaz."},
    {s:"G7, dünyanın en büyük yedi ekonomisini bir araya getiren gruptur.",ans:true,exp:"G7: ABD, Japonya, Almanya, Fransa, Birleşik Krallık, İtalya ve Kanada'dan oluşur. Türkiye G7 üyesi değildir."},
    {s:"Türkiye, 2023 yılında cumhuriyetin 100. kuruluş yıl dönümünü kutlamıştır.",ans:true,exp:"Türkiye Cumhuriyeti 29 Ekim 2023'te 100. kuruluş yıl dönümünü kutlamıştır."},
  ],
  tck:[
    {s:"TCK'ya göre kasten öldürmenin temel cezası ağırlaştırılmış müebbet hapistir.",ans:false,exp:"TCK m.81: Temel ceza müebbet hapistir. Ağırlaştırılmış müebbet m.82'deki nitelikli haller içindir."},
    {s:"Olası kast ile taksir aynı hukuki kavramdır.",ans:false,exp:"Olası kastta fail sonucu kabullenerek hareket eder; taksirde sonuç öngörülmemiş ya da istenmemiştir."},
    {s:"Suça teşebbüste indirimli ceza uygulanır.",ans:true,exp:"TCK m.35/2: Teşebbüs halinde ceza indirimli uygulanır."},
    {s:"12 yaşından küçük çocuklar Türk hukukunda cezai sorumluluk taşır.",ans:false,exp:"TCK m.31/1: 12 yaşını doldurmamış çocuklar hakkında ceza kovuşturması yapılamaz."},
    {s:"Meşru müdafaa koşullarından biri saldırı ile savunma arasında orantı bulunmasıdır.",ans:true,exp:"TCK m.25: Meşru müdafaanın koşullarından biri orantılılıktır."},
    {s:"TCK'da kanunsuz suç ve ceza olmaz ilkesi kabul edilmektedir.",ans:true,exp:"TCK m.2: Kanunsuz suç ve ceza olmaz ilkesi Türk ceza hukukunun temel ilkesidir."},
    {s:"Rüşvet suçunda yalnızca rüşveti alan kişi cezalandırılır.",ans:false,exp:"TCK m.252: Rüşvet alan ve veren her iki taraf da ayrı ayrı cezalandırılır."},
    {s:"Bilinçli taksir ile olası kast aynı şeydir.",ans:false,exp:"Bilinçli taksirde fail sonucu öngörür fakat istemez; olası kastta ise kabullenir. Hukuki sorumlulukları farklıdır."},
    {s:"TCK'ya göre 15-17 yaş arası gençler tam ceza sorumluluğu taşır.",ans:false,exp:"TCK m.31/2: 15-17 yaş arası için ceza indirimli uygulanır; tam sorumluluk 18 yaşında başlar."},
    {s:"Zorunluluk hâli ceza sorumluluğunu kaldırabilir.",ans:true,exp:"TCK m.25/2: Ağır ve muhakkak tehlikeyi başka türlü bertaraf etme imkânı yoksa zorunluluk hâli ceza sorumluluğunu kaldırabilir."},
    {s:"TCK'ya göre taksirle öldürme, kasten öldürme ile aynı cezaya tabidir.",ans:false,exp:"TCK m.85: Taksirle öldürme cezası, kasten öldürme cezasından (m.81) çok daha düşüktür."},
    {s:"Uyuşturucu madde kullanmak TCK kapsamında suçtur.",ans:true,exp:"TCK m.191: Uyuşturucu veya uyarıcı madde kullanmak suçtur; kanunda tedavi ve denetimli serbestlik hükümleri de yer almaktadır."},
    {s:"Türk Ceza Kanunu'nda ölüm cezasına yer verilmektedir.",ans:false,exp:"Ölüm cezası Türkiye'de 2002'de kaldırılmış, 2004 Anayasa değişikliğiyle anayasal güvence altına alınmıştır."},
    {s:"Görevi kötüye kullanma suçunda fail yalnızca kamu görevlisi olabilir.",ans:true,exp:"TCK m.257: Görevi kötüye kullanma özgü bir suçtur; faili ancak kamu görevlisi olabilir."},
    {s:"Haksız tahrik cezayı tamamen kaldıran bir nedendir.",ans:false,exp:"TCK m.29: Haksız tahrik cezayı kaldırmaz; ağır tahrik durumunda 1/4 ile 3/4 oranında indirim uygulanır."},
    {s:"Zimmet suçunun faili ancak kamu görevlisi olabilir.",ans:true,exp:"TCK m.247: Zimmet özgü bir suçtur; özel sektör çalışanları zimmet suçunun faili olamaz."},
    {s:"TCK m.2 kanunilik ilkesini düzenlemektedir.",ans:true,exp:"TCK m.2: Kanunsuz suç ve ceza olmaz ilkesi — hiçbir eylem kanunda suç olarak tanımlanmadan cezalandırılamaz."},
    {s:"Rüşvet suçunda yalnızca rüşveti alan kişi cezalandırılır.",ans:false,exp:"TCK m.252: Rüşvet alan ve veren her iki taraf da ayrı ayrı cezalandırılır."},
    {s:"TCK'ya göre 15–17 yaş arası gençler için ceza indirimi uygulanır.",ans:true,exp:"TCK m.31/2: 15–17 yaş grubundaki gençler için ceza indirimli uygulanır; tam sorumluluk 18 yaşında başlar."},
    {s:"TCK'ya göre suçun manevi unsuru kast ve taksiri kapsar.",ans:true,exp:"TCK m.21–22: Manevi unsur doğrudan kast, olası kast ile bilinçsiz ve bilinçli taksiri kapsar."},
  ],
  cmk:[
    {s:"Tutuklama kararı Cumhuriyet Savcısı tarafından verilir.",ans:false,exp:"CMK m.100: Tutuklama kararı savcının talebi üzerine sulh ceza hâkimi tarafından verilir."},
    {s:"Hukuka aykırı yollarla elde edilen deliller Türk hukukunda kullanılabilir.",ans:false,exp:"CMK m.206/2-a: Hukuka aykırı yollarla elde edilen deliller reddedilir."},
    {s:"Uzlaştırma her suç türüne uygulanabilir.",ans:false,exp:"Uzlaştırma yalnızca kanunda sayılan belirli suçlara uygulanır."},
    {s:"Ceza muhakemesinde ispat yükü savcılığa aittir.",ans:true,exp:"Masumiyet karinesi gereği ispat yükü savcılıktadır; şüphe sanık lehine yorumlanır."},
    {s:"İstinafa başvuru süresi kararın tebliğinden itibaren 30 gündür.",ans:false,exp:"CMK m.273: İstinaf başvuru süresi 15 gündür. Hak düşürücü süre."},
    {s:"Adli kontrol tedbirleri tutuklama yerine uygulanabilen daha hafif tedbirlerdir.",ans:true,exp:"CMK m.109: Yurt dışı çıkış yasağı, imza yükümlülüğü, konut hapsi gibi tedbirler tutuklamaya alternatiftir."},
    {s:"Gözaltı süresi toplu suçlarda 5 güne kadar uzatılabilir.",ans:false,exp:"CMK m.91: Toplu suçlarda gözaltı süresi en fazla 3 güne kadar uzatılabilir."},
    {s:"Ağır ceza mahkemesinin görevine giren suçlarda tutukluluk süresi en fazla 2 yıldır.",ans:true,exp:"CMK m.102: Ağır ceza mahkemesi görev alanında tutukluluk 2 yıl; zorunluluk halinde 3 yıla uzatılabilir."},
    {s:"Suçüstü halinde herkes yakalama yapabilir.",ans:true,exp:"CMK m.90: Suçüstü hâlinde herkes yakalama yapabilir; kişi derhâl kolluğa teslim edilmelidir."},
    {s:"Delil yasakları sadece ceza mahkemelerinde geçerlidir.",ans:false,exp:"Delil yasakları tüm yargılama aşamalarında geçerlidir; hukuka aykırı delil soruşturma aşamasında da kullanılamaz."},
    {s:"Cumhuriyet Savcısı hem suçluluk hem de beraat delillerini araştırmakla yükümlüdür.",ans:true,exp:"CMK m.160: Savcı yalnızca aleyhte değil lehte delilleri de araştırmak zorundadır; tarafsız yargı makamı olma zorunluluğu buradan kaynaklanır."},
    {s:"Tanıklıktan çekinme hakkı şüphelinin yakın akrabalarına tanınmaktadır.",ans:true,exp:"CMK m.45: Şüpheli/sanığın üst-alt soyu, eşi ve bazı yakın akrabaları tanıklıktan çekinebilir."},
    {s:"Şüpheli ifade vermeden önce susma hakkını kullanabilir.",ans:true,exp:"CMK m.147: İfade almadan önce şüpheliye hakları okunur; susma hakkı temel güvencelerden biridir."},
    {s:"İddianame Sulh Ceza Hâkimi tarafından düzenlenir.",ans:false,exp:"İddianame Cumhuriyet Savcısı tarafından hazırlanır; Sulh Ceza Hâkimi soruşturma aşamasında özgürlüğü kısıtlayıcı tedbirlere karar verir."},
    {s:"Beraat kararı kesinleştikten sonra aynı suç için tekrar yargılama açılamaz.",ans:true,exp:"Non bis in idem ilkesi gereği kesinleşmiş beraat kararından sonra aynı fiilden dolayı ikinci kez yargılama yapılamaz."},
    {s:"Ağır ceza mahkemesinde tutukluluk süresi zorunluluk halinde 3 yıla uzatılabilir.",ans:true,exp:"CMK m.102: Ağır ceza mahkemesi görev alanında tutukluluk süresi 2 yıl olup zorunluluk halinde 3 yıla uzatılabilir."},
    {s:"Şikâyete bağlı suçlarda savcı, şikâyet olmaksızın re'sen soruşturma başlatabilir.",ans:false,exp:"Şikâyete bağlı suçlarda mağdurun şikâyeti olmadan savcı re'sen harekete geçemez."},
    {s:"Yeniden yargılama yolu yalnızca sanık lehine olan haller için öngörülmüştür.",ans:true,exp:"CMK m.311 vd.: Yeniden yargılama sanık lehine koşullar gerçekleştiğinde talep edilebilir; sanık aleyhine yeniden yargılama mümkün değildir."},
    {s:"Adli kontrol tedbirleri tutuklamaya alternatif olarak uygulanabilir.",ans:true,exp:"CMK m.109: Yurt dışı çıkış yasağı, imza yükümlülüğü, konut hapsi gibi adli kontrol tedbirleri tutuklamanın daha hafif alternatifidir."},
    {s:"Ceza muhakemesinde ispat yükü savcılığa aittir.",ans:true,exp:"Masumiyet karinesi gereği sanığın suçluluğunu ispat yükü savcılığa aittir; şüphe sanık lehine yorumlanır."},
  ],
  analitik:[
    {s:"Tümdengelim yönteminde genel öncülden özel sonuç çıkarılır.",ans:true,exp:"Tümdengelim (dedüksiyon): Genel öncülden özel sonuca ulaşma; sonuç zorunludur."},
    {s:"'Post hoc ergo propter hoc' yanılgısı kişiye saldırma anlamına gelir.",ans:false,exp:"'Post hoc' yanılgısı ardışıklıktan nedensellik çıkarmaktır. Kişiye saldırma 'ad hominem'dir."},
    {s:"Harmonik ortalama, eşit mesafeli gidiş-dönüş problemlerinde kullanılır.",ans:true,exp:"Eşit mesafe farklı hız problemlerinde harmonik ortalama kullanılır: 2÷(1/v₁+1/v₂)."},
    {s:"4 kişi 6 günde bitirdiği işi, 8 kişi 3 günde bitirir.",ans:true,exp:"Toplam iş = 4×6 = 24 kişi-gün. 8 kişi: 24÷8 = 3 gün."},
    {s:"'Saman Adam' yanılgısı rakibin asıl argümanını güçlendirmeyi ifade eder.",ans:false,exp:"Saman Adam yanılgısı, rakibin argümanını çarpıtarak daha zayıf versiyonuna saldırmaktır."},
    {s:"Tümevarım yönteminde ulaşılan sonuç kesin olarak doğrudur.",ans:false,exp:"Tümevarımda sonuç olasıdır, kesin değildir; yeni bir gözlem sonucu çürütebilir."},
    {s:"2, 6, 18, 54 dizisinde bir sonraki sayı 162'dir.",ans:true,exp:"Her sayı bir öncekinin 3 katıdır: 54×3=162."},
    {s:"'Ad hominem' yanılgısı argümanın içeriğine saldırmayı ifade eder.",ans:false,exp:"Ad hominem, argümanı öne süren kişiye saldırmaktır; içeriğe değil."},
    {s:"Yüzde hesabında 'Parça = Toplam × (Yüzde ÷ 100)' formülü kullanılır.",ans:true,exp:"Temel yüzde formülü: Parça = Toplam × (Yüzde ÷ 100)."},
    {s:"Abdüksiyon, genel öncülden kesin sonuç çıkarma yöntemidir.",ans:false,exp:"Abdüksiyon mevcut verileri en iyi açıklayan hipotezi öne sürmektir; kesin sonuç değil olasılıklı hipotez üretir."},
  ,
    {s:"Bir beşgenin iç açıları toplamı 540 derecedir.",ans:true,exp:"Doğru. (5-2) × 180 = 540°. Formül: (n-2) × 180°."},
    {s:"'Tüm A\u2019lar B\u2019dir. Hiçbir B C değildir.' önermelerinden 'bazı A\u2019lar C\u2019dir' sonucu kesinlikle çıkar.",ans:false,exp:"Yanlış. Tüm A'lar B'dir + Hiçbir B C değildir → Hiçbir A C değildir. 'Bazı A'lar C'dir' sonucu çıkmaz; tam tersi çıkar."},
    {s:"4 kişi 6 günde bitiren işi 8 kişi 3 günde bitirir.",ans:true,exp:"Doğru. Toplam iş = 4 × 6 = 24 kişi-gün. 8 kişi: 24 ÷ 8 = 3 gün."},
    {s:"C(5,2) = 20'dir.",ans:false,exp:"Yanlış. C(5,2) = (5×4) ÷ (2×1) = 10. Kombinasyon formülü: n! ÷ (r! × (n-r)!)."},
    {s:"200 TL'lik malı %20 kâr ile satarsanız satış fiyatı 240 TL olur.",ans:true,exp:"Doğru. Kâr: 200 × 0,20 = 40 TL. Satış: 200 + 40 = 240 TL."},
    {s:"100'ün %15'i 15'tir.",ans:true,exp:"100 × 0,15 = 15."},
    {s:"3 günde 9 iş yapan bir kişi 7 günde 21 iş yapar.",ans:true,exp:"Günlük iş: 9 ÷ 3 = 3. 7 günde: 3 × 7 = 21."},
    {s:"A > B ve B > C ise A > C olmak zorundadır.",ans:true,exp:"Geçişlilik (transitivity): A > B ve B > C ise A > C kesin olarak doğrudur."},
    {s:"1'den 10'a kadar çift sayıların toplamı 30'dur.",ans:true,exp:"2 + 4 + 6 + 8 + 10 = 30."},
    {s:"Bir dikdörtgenin alanı (en + boy) × 2 formülüyle hesaplanır.",ans:false,exp:"Alan = en × boy. (en + boy) × 2 formülü alanı değil çevreyi verir."},
  ],
  // ── Kanun Bazlı D/Y Kartları ──────────────────
  kab:[
    {s:"Kabahatler Kanunu kapsamındaki yaptırımlar idari nitelikte olup adli sicile işlenmez.",ans:true,exp:"5326 sayılı Kabahatler Kanunu: Kabahatlerin yaptırımı idari para cezası veya güvenlik tedbiridir; hapis cezası öngörülmez ve adli sicile yansımaz."},
    {s:"İdari para cezasına itiraz için 30 gün içinde idare mahkemesine başvurulur.",ans:false,exp:"5326 sayılı Kabahatler Kanunu: İtiraz, kararın tebliğinden itibaren 15 gün içinde sulh ceza hâkimliğine yapılır. Süre 30 gün değil, 15 gündür."},
    {s:"Kabahatlerde zamanaşımı süresi 3 yıldır.",ans:true,exp:"5326 sayılı Kabahatler Kanunu m.20: Kabahatlerde zamanaşımı süresi 3 yıldır; fiilin işlendiği tarihten itibaren başlar."},
    {s:"Suçüstü halinde kolluk görevlisi bizzat idari para cezasına karar verebilir.",ans:true,exp:"5326 sayılı Kabahatler Kanunu: Suçüstü halinde kolluk görevlisi idari para cezasına karar verebilir. Diğer hallerde yetkili makam (vali, belediye başkanı vb.) karar verir."},
    {s:"Kabahatler Kanunu, hapis cezasını da yaptırım olarak öngörmektedir.",ans:false,exp:"5326 sayılı Kabahatler Kanunu kapsamında hapis cezası bulunmaz; yaptırımlar idari para cezası ve güvenlik tedbirlerinden ibarettir."},
    {s:"Kabahatler Kanunu, eski TCK'daki suç-cürüm ayrımının kaldırılmasından sonra düzenlenmiştir.",ans:true,exp:"Yeni TCK ile cürüm/kabahat ayrımı kaldırılmış; kabahatler 5326 sayılı Kabahatler Kanunu'nda bağımsız olarak düzenlenmiştir."},
  ],
  tmk:[
    {s:"TMK kapsamında terör suçlarında gözaltı süresi hâkim kararıyla 7 güne uzatılabilir.",ans:true,exp:"3713 sayılı TMK m.10: Terör suçlarında savcı kararıyla 4 güne, hâkim kararıyla 7 güne kadar uzatılabilir. Normal suçlarda azami 4 gündür."},
    {s:"Terör örgütü üyesi olan kişiye 5–10 yıl hapis cezası verilir.",ans:true,exp:"3713 sayılı TMK: Terör örgütü üyesi 5–10 yıl hapis alır. Örgütü kuran veya yöneten kişi ise 10–15 yıl hapis ile cezalandırılır."},
    {s:"TMK kapsamındaki suçlarda ceza alt sınırından indirim uygulanabilir.",ans:false,exp:"Terör suçlarında ceza alt sınırından indirim yapılamaz; ayrıca erteleme ve HAGB de uygulanmaz."},
    {s:"TMK kapsamında gözaltı süresini uzatan hâkim sulh ceza hâkimidir.",ans:false,exp:"3713 sayılı TMK m.10: Gözaltı uzatma kararını ağır ceza mahkemesi nöbetçi hâkimi verir, sulh ceza hâkimi değil."},
    {s:"Terör örgütü kuran veya yöneten kişi 10–15 yıl hapis cezasıyla cezalandırılır.",ans:true,exp:"3713 sayılı TMK: Örgütü kuran/yöneten 10–15 yıl hapis alır. Bu suçlarda erteleme ve HAGB uygulanmaz."},
    {s:"Terör suçlarında hükmün açıklanmasının geri bırakılması (HAGB) uygulanabilir.",ans:false,exp:"Terör suçlarında HAGB uygulanmaz; ceza ertelenmez ve alt sınırdan indirim de yapılamaz."},
  ],
  aile:[
    {s:"6284 sayılı Kanun kapsamında önleyici tedbir kararı yalnızca aile mahkemesi hâkimi tarafından verilebilir.",ans:true,exp:"6284 sayılı Ailenin Korunması Kanunu: Koruyucu tedbirler hâkim ve mülki amir tarafından verilebilirken, önleyici tedbirler (uzaklaştırma, iletişim yasağı vb.) yalnızca aile mahkemesi hâkimi tarafından verilebilir."},
    {s:"Tedbir kararları kural olarak en fazla 6 ay süreyle verilebilir.",ans:true,exp:"6284 sayılı Kanun m.8: Tedbir kararları kural olarak en fazla 6 ay süreyle verilir; zorunluluk halinde uzatılabilir."},
    {s:"6284 kapsamında tedbir kararına aykırılık halinde 3–10 gün zorlama hapsi uygulanır.",ans:true,exp:"6284 sayılı Kanun: Tedbir kararına aykırı davranan kişiye 3–10 gün zorlama hapsi uygulanır. Aykırılığın tekrarında süre artırılır."},
    {s:"6284 kapsamındaki suçlarda şikâyetten vazgeçilmesi kovuşturmayı durdurur.",ans:false,exp:"6284 kapsamındaki suçlar kamu davası niteliğindedir; şikâyetten vazgeçme kovuşturmayı etkilemez. Suçüstü halinde doğrudan gözaltı yapılabilir."},
    {s:"Zorlama hapsi adli sicile işlenmez.",ans:true,exp:"6284 sayılı Kanun: Zorlama hapsi ceza niteliği taşımaz ve adli sicile yansımaz; idari yaptırım niteliğindedir."},
    {s:"Koruyucu tedbir kararları hem hâkim hem de mülki amir tarafından verilebilir.",ans:true,exp:"6284 sayılı Kanun: Mağduru korumaya yönelik koruyucu tedbirler hem hâkim hem de mülki amir tarafından verilebilir. Önleyici tedbirler ise yalnızca hâkime aittir."},
  ],
  kacak:[
    {s:"5607 sayılı Kanun'a göre kaçakçılık konusu eşyanın müsaderesi zorunludur.",ans:true,exp:"5607 sayılı Kaçakçılıkla Mücadele Kanunu m.13: Kaçakçılık konusu eşyanın müsaderesi zorunludur; hâkimin takdir yetkisi yoktur."},
    {s:"Örgütlü kaçakçılıkta temel ceza 1/3 oranında artırılır.",ans:false,exp:"5607 sayılı Kanun: Örgütlü kaçakçılıkta temel ceza 1/2 (yarı) oranında artırılır, 1/3 değil."},
    {s:"Akaryakıt kaçakçılığı 2–5 yıl hapis cezasını gerektirmektedir.",ans:true,exp:"5607 sayılı Kaçakçılıkla Mücadele Kanunu m.4: Akaryakıt ve tütün mamulleri kaçakçılığı 2–5 yıl hapis cezasına tabidir."},
    {s:"Nakilde kullanılan araç bireysel kaçakçılıkta da zorunlu olarak müsadere edilir.",ans:false,exp:"5607 sayılı Kanun: Nakil aracı örgütlü kaçakçılıkta zorunlu, bireysel kaçakçılıkta ise ihtiyari (takdire bağlı) olarak müsadere edilebilir."},
    {s:"5607 kapsamında kaçak malı satmak da suç oluşturur.",ans:true,exp:"5607 sayılı Kaçakçılıkla Mücadele Kanunu: Kaçak malı satmak, satın almak, bulundurmak ve nakletmek de aynı suç kapsamında değerlendirilir."},
    {s:"Kaçakçılık suçuna teşebbüs, tamamlanmış kaçakçılık gibi cezalandırılır.",ans:true,exp:"5607 sayılı Kanun: Kaçakçılık suçuna teşebbüs tamamlanmış suç gibi cezalandırılır."},
  ],
  trafik:[
    {s:"2918 sayılı KTK'ya göre hafif taşıt sürücüsü için yasal alkol sınırı 0,50 promildir.",ans:true,exp:"2918 sayılı KTK m.48: Hafif taşıt sürücüleri için yasal alkol sınırı 0,50 promildir. Bu sınırın aşılması idari yaptırıma tabidir."},
    {s:"Ticari araç sürücüleri için alkol sınırı 0,50 promildir.",ans:false,exp:"2918 sayılı KTK m.48: Ticari araç sürücüleri ve kamu taşıtı kullananlar için alkol sınırı 0,20 promildir. 0,50 promil hafif taşıt sürücülerine uygulanır."},
    {s:"Sürücünün alkol oranının 1,00 promili aşması halinde TCK m.179 kapsamında cezai kovuşturma başlatılır.",ans:true,exp:"KTK m.48 ve TCK m.179: 1,00 promil üzerinde alkollü araç kullanmak trafik güvenliğini tehlikeye atmak suçunu oluşturur; cezai kovuşturma başlatılır."},
    {s:"Alkol oranı 0,50–1,00 promil arasında olan sürücüler cezai kovuşturmaya tabidir.",ans:false,exp:"0,50–1,00 promil arası yalnızca idari yaptırıma (ehliyete el koyma, para cezası) tabidir; cezai kovuşturma yapılmaz. 1,00 promilin üzeri cezai yaptırıma tabidir."},
    {s:"Tüm sürücüler için aynı alkol sınırı uygulanır.",ans:false,exp:"KTK m.48: Hafif taşıt sürücülerine 0,50 promil, ticari araç ve kamu taşıtı sürücülerine 0,20 promil sınırı uygulanır."},
  ],
  tanik:[
    {s:"5726 sayılı Kanun'a göre tanık koruma kararı Cumhuriyet savcısı tarafından tek başına verilebilir.",ans:false,exp:"5726 sayılı Tanık Koruma Kanunu m.4: Koruma kararı; savcının talebi ve hâkimin onayıyla ağır ceza mahkemesi bünyesindeki koruma kurulu tarafından verilir. Savcı tek başına karar veremez."},
    {s:"En ağır tanık koruma tedbiri kimlik değişikliğidir.",ans:true,exp:"5726 sayılı Kanun m.3: Tanık koruma tedbirleri beş kademede uygulanır. En hafifi kimlik/adres bilgilerinin gizlenmesi, en ağırı kimlik değişikliğidir."},
    {s:"Korunan tanığın kimlik bilgileri savunma hakkı gereği sanığa mutlaka açıklanmak zorundadır.",ans:false,exp:"5726 sayılı Kanun: Korunan tanığın kimlik bilgileri sanığa, müdafiine ve hatta dosyaya bile gizli tutulabilir. Tanığın güvenliği öncelik taşır."},
    {s:"Korunan tanık ses/görüntü bağlantısıyla ifade verebilir.",ans:true,exp:"5726 sayılı Tanık Koruma Kanunu: Korunan tanık doğrudan mahkemede ifade vermek yerine ses veya görüntü bağlantısı aracılığıyla da ifade verebilir."},
    {s:"Tanık koruma kararı aile mahkemesi tarafından verilir.",ans:false,exp:"5726 sayılı Kanun: Koruma kararı, ağır ceza mahkemesi bünyesindeki koruma kurulu tarafından verilir. Aile mahkemesi bu konuda yetkili değildir."},
    {s:"Korunan tanığın bilgileri gerektiğinde dosyaya da gizli tutulabilir.",ans:true,exp:"5726 sayılı Kanun: Korunan tanığın bilgileri dosyaya bile gizli tutulabilir; sanık ve müdafi bu bilgilere ulaşamaz."},
  ],
  pasaport:[
    {s:"Pasaport, İçişleri Bakanlığı tarafından düzenlenir.",ans:true,exp:"5682 sayılı Pasaport Kanunu: Pasaport, TC adına İçişleri Bakanlığı tarafından düzenlenir. Yurt dışında konsolosluklarca da verilebilir."},
    {s:"Hususi (gri) pasaport tüm TC vatandaşlarına verilir.",ans:false,exp:"5682 sayılı Kanun m.14: Hususi pasaport (gri) kamu görevlileri ve ailelerine verilir. Tüm vatandaşlara verilen bordo pasaporttur (umuma mahsus)."},
    {s:"İcra-iflas takibinde borçlunun pasaportunun iptali için mahkeme kararı gerekir.",ans:true,exp:"5682 sayılı Pasaport Kanunu m.22: Borçlunun pasaportunun iptali veya verilmemesi için mahkeme kararı gerekmektedir."},
    {s:"Diplomatik pasaport (siyah) kamu hizmetiyle yurt dışına gidenlere verilir.",ans:false,exp:"5682 sayılı Kanun: Kamu hizmetiyle yurt dışına gidenler yeşil (hizmet) pasaport alır. Siyah (diplomatik) pasaport yalnızca diplomatik göreve atananlara verilir."},
    {s:"Tutuklu ve hükümlüler ayrıca mahkeme kararı olmaksızın pasaport alamazlar.",ans:true,exp:"5682 sayılı Pasaport Kanunu: Tutuklu veya hükümlü bulunanlar doğrudan pasaport alamazlar; bu durum ayrı bir karar gerektirmeksizin uygulanır."},
    {s:"Yurt dışında konsolosluklar TC adına pasaport düzenleyebilir.",ans:true,exp:"5682 sayılı Pasaport Kanunu: Pasaport yurt içinde İçişleri Bakanlığı, yurt dışında ise TC konsoloslukları tarafından düzenlenebilir."},
  ],
  kvkk:[
    {s:"Kişisel veri ihlalinde KVK Kuruluna bildirim süresi 48 saattir.",ans:false,exp:"6698 sayılı KVKK: Kişisel veri ihlalinin öğrenilmesinden itibaren veri sorumlusu 72 saat içinde KVK Kuruluna bildirimde bulunmalıdır."},
    {s:"KVK Kurulu 9 üyeden oluşmaktadır.",ans:true,exp:"6698 sayılı KVKK m.20: KVK Kurulu 9 üyeden oluşur; 5 üye TBMM, 4 üye Cumhurbaşkanı tarafından seçilir."},
    {s:"Sağlık verileri özel nitelikli kişisel veri sayılmaktadır.",ans:true,exp:"6698 sayılı KVKK m.6: Sağlık ve cinsel hayata ilişkin veriler özel nitelikli kişisel veri kategorisindedir; daha sıkı koruma altındadır."},
    {s:"KVK Kurulunun 5 üyesi Cumhurbaşkanı tarafından seçilir.",ans:false,exp:"6698 sayılı KVKK m.20: KVK Kurulunun 5 üyesi TBMM, 4 üyesi Cumhurbaşkanı tarafından seçilir. Cumhurbaşkanının seçtiği üye sayısı 4'tür."},
    {s:"Veri ihlali ilgili kişileri etkiliyorsa onlara da gecikmeksizin bildirim yapılmalıdır.",ans:true,exp:"6698 sayılı KVKK: İhlal ilgili kişileri etkiliyorsa KVK Kuruluna bildirime ek olarak ilgili kişilere de gecikmeksizin bildirim yapılmak zorundadır."},
    {s:"Sağlık verileri sır saklama yükümlülüğü olmayan herhangi bir kişi tarafından işlenebilir.",ans:false,exp:"6698 sayılı KVKK m.6: Sağlık verileri yalnızca sır saklama yükümlülüğü altındaki sağlık personeli tarafından ve koruyucu hekimlik, teşhis, tedavi kapsamında işlenebilir."},
  ],
  kimlik:[
    {s:"Konaklama yerleri misafir bilgilerini 24 saat içinde güvenlik birimine bildirmek zorundadır.",ans:true,exp:"1774 sayılı Kimlik Bildirme Kanunu m.1–2: Otel, motel, pansiyon vb. yerler misafirin girişinden itibaren 24 saat içinde kimlik bilgilerini emniyet veya jandarmaya bildirmekle yükümlüdür."},
    {s:"Kimlik bildirme kayıtları en az 5 yıl muhafaza edilmelidir.",ans:true,exp:"1774 sayılı Kimlik Bildirme Kanunu m.3–4: Konaklama yerlerince tutulan kimlik kayıtları en az 5 yıl süreyle muhafaza edilmek zorundadır."},
    {s:"Kimlik bildirme kaydının denetim yetkisi Ticaret Bakanlığı'na aittir.",ans:false,exp:"1774 sayılı Kimlik Bildirme Kanunu m.6: Denetim yetkisi emniyet ve jandarma birimlerine aittir. Ticaret Bakanlığı bu konuda yetkili değildir."},
    {s:"Yabancı misafirler kimlik bildirme yükümlülüğü kapsamı dışındadır.",ans:false,exp:"1774 sayılı Kimlik Bildirme Kanunu: Yükümlülük hem Türk hem de yabancı misafirleri kapsamaktadır; herhangi bir ayrım öngörülmemiştir."},
    {s:"Kimlik bildirme yükümlülüğünü ihlal eden işletme sahiplerine idari para cezası uygulanır.",ans:true,exp:"1774 sayılı Kimlik Bildirme Kanunu m.6: Yükümlülüğü ihlal eden işletme sahiplerine idari para cezası uygulanır."},
    {s:"Elektronik bildirim sistemleri (GÖÇ-NET vb.) üzerinden yapılan bildirimler de yükümlülüğü karşılar.",ans:true,exp:"1774 sayılı Kimlik Bildirme Kanunu: Elektronik bildirim sistemleri üzerinden yapılan bildirimler de kanunun öngördüğü yükümlülüğü karşılamaktadır."},
  ],
  dmk:[
    {s:"Devlet memurluğundan çıkarma cezasına Yüksek Disiplin Kurulu karar verir.",ans:true,exp:"657 sayılı Devlet Memurları Kanunu m.125: En ağır disiplin cezası olan devlet memurluğundan çıkarma, Yüksek Disiplin Kurulu tarafından verilir."},
    {s:"10 yılı aşkın kıdeme sahip devlet memurunun yıllık izni 30 gündür.",ans:true,exp:"657 sayılı DMK m.177: 1–10 yıl kıdem için yıllık izin 20 gün, 10 yılı aşkın kıdem için 30 gündür."},
    {s:"Devlet memuru olabilmek için en az üniversite mezunu olmak gerekir.",ans:false,exp:"657 sayılı DMK m.48: Memur olabilmek için en az ortaöğretim (lise) mezunu olmak yeterlidir. Üniversite mezuniyeti her kadro için zorunlu değildir."},
    {s:"Devlet memurları Anayasa'ya göre grev hakkına sahiptir.",ans:false,exp:"Devlet memurlarının grev hakkı yoktur. Anayasa m.54 grev hakkını işçilere tanımış; 657 sayılı Kanun çerçevesinde memurlar greve gidemez."},
    {s:"Uyarma disiplin cezasına da Yüksek Disiplin Kurulu karar verir.",ans:false,exp:"657 sayılı DMK: Uyarma, kınama ve aylıktan kesme cezaları ilgili disiplin kurullarınca verilir. Devlet memurluğundan çıkarma kararı ise Yüksek Disiplin Kuruluna aittir."},
    {s:"1–10 yıl arasında kıdeme sahip devlet memurunun yıllık izni 20 gündür.",ans:true,exp:"657 sayılı DMK m.177: 1–10 yıl arasında kıdemi olan memurların yıllık izin hakkı 20 gündür. 10 yılı aşkın kıdemde bu süre 30 güne çıkar."},
  ],
  vatandaslik:[
    {s:"Türk vatandaşlığının doğumla kazanılmasında birincil ilke soy bağıdır.",ans:true,exp:"5901 sayılı Türk Vatandaşlığı Kanunu m.6–7: Doğumla vatandaşlık kazanımında birincil ilke ius sanguinis (soy bağı) ilkesidir. Doğum yeri ilkesi tamamlayıcı niteliktedir."},
    {s:"Evlenme yoluyla Türk vatandaşlığı kazanmak için en az 3 yıl evli kalmak gerekir.",ans:true,exp:"5901 sayılı TVK m.16: Yabancı eşin Türk vatandaşlığı kazanabilmesi için TC vatandaşıyla en az 3 yıl evli kalmak ve evlilik birliği içinde birlikte yaşamak gerekir."},
    {s:"Yetkili makam kararıyla vatandaşlık kazanmak için Türkiye'de 3 yıl ikamet yeterlidir.",ans:false,exp:"5901 sayılı TVK m.11: Yetkili makam kararıyla vatandaşlık kazanmak için kesintisiz 5 yıl ikamet zorunludur. 3 yıl yeterli değildir."},
    {s:"Türk vatandaşlığı yalnızca doğum yolu ile kazanılabilir.",ans:false,exp:"5901 sayılı TVK: Vatandaşlık; doğumla, yetkili makam kararıyla, evlenme yoluyla ve evlat edinmeyle de kazanılabilir. Yalnızca doğumla değil."},
    {s:"Evlilik sona erse de evlenerek kazanılan Türk vatandaşlığı kaybedilmez.",ans:true,exp:"5901 sayılı TVK: Evlilik yoluyla kazanılan vatandaşlık, evliliğin sona ermesiyle otomatik olarak kaybedilmez. Vatandaşlıktan çıkarma için ayrı bir işlem gerekir."},
    {s:"TC vatandaşı babanın yurt dışında doğan çocuğu otomatik olarak Türk vatandaşı sayılır.",ans:true,exp:"5901 sayılı TVK m.6: TC vatandaşı anne veya babanın çocuğu, doğum yeri ne olursa olsun soy bağı ilkesiyle Türk vatandaşı olur."},
  ],
  resmiyas:[
    {s:"Resmî yazışmada 'Olur' belgesi makam içi onay için kullanılır.",ans:false,exp:"Resmî Yazışma Yönetmeliği: 'Onay' belgesi makam içi onay için; 'Olur' belgesi ise üst makamdan alınan yazılı izin için kullanılır."},
    {s:"Gizlilik dereceli yazılar çift zarfla gönderilir.",ans:true,exp:"Resmî Yazışma Yönetmeliği: Gizlilik dereceli yazılar çift zarfla gönderilir. Dış zarfta yalnızca alıcı adresi, iç zarfta gizlilik derecesi belirtilir."},
    {s:"Resmî yazının imzasında ad soyad büyük, unvan da büyük harfle yazılır.",ans:false,exp:"Resmî Yazışma Yönetmeliği: İmzanın altında ad soyad büyük harfle, unvan ise küçük harfle yazılır."},
    {s:"Kayıt numarası formatı: Birim kodu / Yıl / Sıra no şeklindedir.",ans:true,exp:"Resmî Yazışma Yönetmeliği: Her yazıya eşsiz kayıt numarası verilir. Format: Birim kodu / Yıl / Sıra no (örn: EGM/2024/001)."},
    {s:"Resmî yazışma arşivleme süresi en az 5 yıldır.",ans:true,exp:"Resmî Yazışma Yönetmeliği: Yazılar dosyalanarak en az 5 yıl kurumsal arşivde saklanır; imha için Devlet Arşivleri mevzuatı uygulanır."},
    {s:"'Paraf', üst makamın onayı anlamına gelir.",ans:false,exp:"Resmî Yazışma Yönetmeliği: Paraf, yetkili imzadan önce yazıyı hazırlayan veya inceleyen kişilerin koyduğu onay işaretidir; üst makam onayı değildir."},
  ],
};

// ════════════════════════════════════════════════
//  BİLGİ KARTLARI
// ════════════════════════════════════════════════