const lawData = {
  tck: {
    name:'Türk Ceza Kanunu (TCK)', short:'TCK',
    articles:[
      {num:'m.2', title:'Kanunilik İlkesi', body:'Kanunun açıkça suç saymadığı bir fiil için kimseye ceza verilemez; kıyas yapılamaz. Suç ve ceza içeren hükümler geniş yorumlanamaz.', tip:'Nullum crimen sine lege — Kanunsuz suç ve ceza olmaz. İdari işlemle suç yaratılamaz.'},
      {num:'m.7', title:'Zaman Bakımından Uygulama', body:'Suç tarihindeki kanun esas alınır. Sonradan yürürlüğe giren lehe kanun kovuşturma ve infaz aşamasında uygulanır.', tip:'Lehe kanun geçmişe yürür; aleyhe kanun yürümez.'},
      {num:'m.20', title:'Ceza Sorumluluğunun Şahsîliği', body:'Kimse başkasının fiilinden dolayı cezalandırılamaz. Tüzel kişiler hakkında ceza yaptırımı uygulanamaz; yalnızca güvenlik tedbiri uygulanabilir.', tip:'Ceza hukukunda müteselsil sorumluluk yoktur.'},
      {num:'m.21', title:'Kast', body:'Doğrudan kast: suçun unsurlarını bilerek ve isteyerek gerçekleştirme. Olası kast: neticeyi öngörüp "olursa olsun" diyerek kabul etme; ceza 1/3–1/2 oranında indirilir.', tip:'Doğrudan = bil + iste. Olası = öngör + kabul et. Olası kastta ceza indirilir.'},
      {num:'m.22', title:'Taksir', body:'Dikkat ve özen yükümlülüğüne aykırılık sonucu neticenin öngörülmeksizin gerçekleştirilmesidir. Bilinçli taksirde fail neticeyi öngörür fakat gerçekleşmeyeceğine güvenir; ceza 1/3–1/2 artırılır.', tip:'"Olmaz sanarak" = bilinçli taksir (ceza artar). "Olursa olsun" = olası kast (farklı suç).'},
      {num:'m.25', title:'Meşru Savunma ve Zorunluluk Hâli', body:'Haksız bir saldırıyı koşullarla orantılı biçimde defetmek zorunda kalarak işlenen fiil cezasızdır. Zorunluluk hâlinde de ceza verilmez.', tip:'4 şart: Haksız saldırı + yakın tehlike + savunma zorunluluğu + orantılılık.'},
      {num:'m.27', title:'Müdafaada Sınırın Aşılması', body:'Meşru savunma sınırı taksirle aşılırsa taksir cezası 1/6–1/3 indirilir. Korku, panik veya şaşkınlıkla sınır aşılmışsa ceza verilmez.', tip:'Panik/korku ile aşılırsa → ceza yok (m.27/2). Taksirle aşılırsa → indirimli taksir cezası.'},
      {num:'m.31', title:'Yaş Küçüklüğü', body:'12 yaş altı: sorumluluk yok. 12–14 yaş: fiili kavrama yeteneğine göre. 15–17 yaş: indirimli sorumluluk. 18+: tam sorumluluk.', tip:'12 altı=sıfır · 12–14=değerlendirme · 15–17=indirim · 18+=tam sorumluluk.'},
      {num:'m.35', title:'Suça Teşebbüs', body:'İcraya başlanıp elinde olmayan nedenlerle tamamlanamamasıdır. Ceza: Ağırlaştırılmış müebbet yerine 13–20 yıl; müebbet yerine 9–15 yıl; diğerlerinde 1/4–3/4 indirim.', tip:'Hazırlık hareketi ≠ İcra hareketi. Gönüllü vazgeçme (m.36) cezasızlık sebebidir.'},
      {num:'m.37–39', title:'Suça İştirak', body:'Müşterek fail (m.37): suçu birlikte gerçekleştiren, asıl cezayı alır. Azmettiren (m.38): suç işlemeye yönlendiren, asıl cezayı alır. Yardım eden (m.39): suçun işlenmesine yardımcı olan, indirimli ceza alır.', tip:'Müşterek fail = tam ceza · Azmettiren = tam ceza · Yardım eden = indirimli ceza.'},
      {num:'m.81–82', title:'Kasten Öldürme', body:'Kasten öldürme (m.81): müebbet hapis. Nitelikli haller (m.82: tasarlayarak, alçakça güdü, eziyet, kan gütme vb.): ağırlaştırılmış müebbet. Taksirle öldürme (m.85): 2–6 yıl.', tip:'Temel: müebbet. Nitelikli (m.82): ağırlaştırılmış müebbet. Taksirle: 2–6 yıl.'},
      {num:'m.86', title:'Kasten Yaralama', body:'Başkasına acı veren veya sağlığını bozan eylem: 1–3 yıl hapis. Basit tıbbi müdahaleyle giderilebilecek yaralama şikâyete bağlıdır: 4 ay–1 yıl veya adli para cezası.', tip:'Şikâyete bağlı basit hâl: 4 ay–1 yıl. Organ kaybı/kemik kırığı/yüzde iz: nitelikli hâl.'},
      {num:'m.106', title:'Tehdit', body:'Hayata, vücuda, cinsel dokunulmazlığa veya malvarlığına zarar verileceğini bildirme: 6 ay–2 yıl hapis. Silahla veya birden fazla kişiyle tehdit ağırlaştırıcı hâldir.', tip:'Söz/yazı/işaret/davranış yeterli. Silahla tehdit cezayı artırır.'},
      {num:'m.109', title:'Kişiyi Hürriyetinden Yoksun Kılma', body:'Kişiyi hukuka aykırı olarak bir yere gitmekten veya bir yerde kalmaktan yoksun bırakma: 1–5 yıl hapis. Kamu görevlisi ya da silahla işlenirse ceza artar.', tip:'Kamu görevlisi veya silahlı işlenirse nitelikli hâl.'},
      {num:'m.125', title:'Hakaret', body:'Somut fiil isnat ederek veya sövme yoluyla kişinin onur/şeref/saygınlığına saldırı: 3 ay–2 yıl hapis. Alenen hakaret cezayı 1/6 artırır.', tip:'Kamu görevlisine görevi nedeniyle hakaret: alt sınır 1 yıla çıkar.'},
      {num:'m.141–142', title:'Hırsızlık', body:'Başkasına ait taşınır malı rızası olmaksızın alma (m.141): 1–3 yıl. Nitelikli hırsızlık (m.142: gece, konuttan, birden fazla kişiyle vb.): 2–7 yıl hapis.', tip:'Şikâyete bağlı değildir. Konut dokunulmazlığıyla birleşirse ayrıca ceza.'},
      {num:'m.157–158', title:'Dolandırıcılık', body:'Hileli davranışla aldatıp haksız çıkar sağlama (m.157): 1–5 yıl + adli para cezası. Nitelikli hâl (m.158: bilişim sistemi, kamu kurumu adına, din/inanç istismarı): 3–10 yıl hapis.', tip:'3 unsur: Hileli davranış + Aldatma + Haksız yarar. Bilişim sistemiyle işlenirse niteliklidir.'},
      {num:'m.220', title:'Suç İşlemek Amacıyla Örgüt Kurma', body:'En az 3 kişiden oluşan hiyerarşik yapı. Örgüt kuran/yöneten: 2–6 yıl; üye olan: 1–3 yıl. Suç işlenmemiş olsa bile örgüt kurma suçu tamamdır.', tip:'3 kişi + hiyerarşi + süreklilik = örgüt. Suç işlenmemiş olsa bile suçtur.'},
      {num:'m.250', title:'İrtikap', body:'Kamu görevlisinin görevinin sağladığı nüfuzu kötüye kullanarak menfaat sağlaması veya sağlanmasına yol açması. İcbar yoluyla: 5–10 yıl; ikna yoluyla: 3–5 yıl.', tip:'İrtikap ≠ Rüşvet: İrtikap baskı/zorlamayla; Rüşvet karşılıklı anlaşmayla gerçekleşir.'},
      {num:'m.252', title:'Rüşvet', body:'Kamu görevlisine görevle ilgili iş karşılığı menfaat sağlama veya sağlanmasına aracılık. Rüşveti alan ve veren her iki taraf: 4–12 yıl hapis. Teklif edilmesi de suçtur.', tip:'Hem veren hem alan eşit ceza alır. Görev ilişkisi şarttır.'},
      {num:'m.257', title:'Görevi Kötüye Kullanma', body:'Görevin gereklerine aykırı hareketle mağduriyet yaratma veya haksız menfaat sağlama: 6 ay–2 yıl. Görevi ihmal: 3 ay–1 yıl. Yalnızca kamu görevlisi faildir (özgü suç).', tip:'Aykırı davranış (6ay–2yıl) ≠ İhmal (3ay–1yıl). Özgü suç: yalnızca kamu görevlisi.'},
      {num:'m.265', title:'Görevi Yaptırmamak İçin Direnme', body:'Kamu görevlisine görevini yapmasını engellemek amacıyla cebir veya tehdit kullanma: 6 ay–3 yıl hapis. Silahla veya birlikte işlenirse ceza artırılır.', tip:'"Mukavemet suçu" olarak da bilinir. Cebir veya tehdit yeterlidir; ikisi birlikte aranmaz.'},
      {num:'m.267', title:'İftira', body:'Suçsuz biri hakkında yetkili makama asılsız ihbarda bulunarak soruşturma başlatılmasına yol açma: 1–4 yıl hapis. Delil uydurmayla yapılırsa ceza artırılır.', tip:'İftira = yalan isnat + yetkili makama bildirim. Hakaret (m.125): alenen kişiye yönelir; iftiradan farklıdır.'},
    ]
  },
  cmk: {
    name:'Ceza Muhakemesi Kanunu (CMK)', short:'CMK',
    articles:[
      {num:'m.2', title:'Temel Tanımlar', body:'Şüpheli: soruşturma evresindeki kişi. Sanık: iddianame kabulünden itibaren kovuşturma evresindeki kişi. Mağdur: suçtan zarar gören. Müdafi: şüpheli/sanığın avukatı.', tip:'Soruşturma → şüpheli. İddianame kabul → sanık. Bu geçiş çok sık sorulur.'},
      {num:'m.90', title:'Herkes Tarafından Yakalama', body:'Suçüstü hâlinde veya kolluğa bildirim imkânı yoksa herkes tarafından yakalama yapılabilir. Yakalayan kişi yakaladığını derhâl kolluğa teslim etmek zorundadır.', tip:'Suçüstü + bildirim imkânsızlığı = herkes yakalayabilir. Kolluğa teslim zorunludur.'},
      {num:'m.91', title:'Gözaltı Süresi', body:'Yakalamadan itibaren en geç 24 saat içinde serbest bırakılır ya da hâkim önüne çıkarılır. Toplu suçlarda savcının yazılı emriyle her seferinde 1 gün, toplam 3 güne kadar uzatılabilir.', tip:'Kural: 24 saat. Toplu suç: +3 gün (savcı kararıyla, her defasında 1 gün). Maks 4 gün.'},
      {num:'m.98', title:'Yakalama Emri', body:'Hâkim ya da savcı tarafından verilebilir. Kolluğun elinden kaçan şüpheli ya da sanık için kolluk da yakalama emri düzenleyebilir.', tip:'Kaçma hâlinde kolluk da yakalama emri düzenleyebilir.'},
      {num:'m.100', title:'Tutuklama Nedenleri', body:'İki şart birlikte aranır: (1) Kuvvetli suç şüphesi + (2) Tutuklama nedeni (kaçma şüphesi veya delil karartma tehlikesi). Katalog suçlarda bu nedenler karine olarak kabul edilir.', tip:'Kuvvetli şüphe + (kaçma VEYA delil karartma) = tutuklama. Karar: yalnızca sulh ceza hâkimi.'},
      {num:'m.102', title:'Tutukluluk Süresi', body:'Ağır ceza mahkemesi görevinde: 2 yıl (zorunlulukta 3 yıla uzatılabilir). Diğer suçlarda: 6 ay (uzatmayla 1 yıla kadar). Her uzatma için ayrı hâkim kararı gerekir.', tip:'Ağır suç: 2 yıl → uzatmayla 3 yıl. Hafif suç: 6 ay → uzatmayla 1 yıl.'},
      {num:'m.109', title:'Adli Kontrol', body:'Tutuklama şartları oluşsa bile uygulanabilecek daha hafif tedbirler: yurt dışı çıkış yasağı, imza yükümlülüğü, konut hapsi, belirli yerlere gitme yasağı. Tutuklama son çaredir.', tip:'Tutuklama yerine önce adli kontrol değerlendirilir. 3 yıl altı suçlarda tutuklama yerine tercih edilmeli.'},
      {num:'m.119', title:'Arama Kararı', body:'Hâkim kararı esastır. Gecikmesinde sakınca varsa savcı yazılı emriyle; savcıya ulaşılamazsa kolluk amiri yazılı emriyle arama yapılabilir. Her iki hâlde de karar 24 saat içinde hâkime sunulur.', tip:'Sıralama: Hâkim → Savcı (acil) → Kolluk amiri (savcıya ulaşılamazsa). Hepsi 24 saatte hâkime.'},
      {num:'m.134', title:'Bilgisayar ve Kütüklerde Arama', body:'İki şart birlikte: (1) Somut delile dayanan kuvvetli şüphe + (2) Başka surette delil elde etme imkânsızlığı. Hâkim kararı zorunludur.', tip:'Çift şart zorunlu. Hâkim kararı olmadan bilgisayara bakılamaz.'},
      {num:'m.135', title:'İletişimin Denetlenmesi', body:'İki şart: (1) Kuvvetli şüphe + (2) Başka türlü delil elde edilememe. Hâkim kararı şart; acil hâlde savcı başlatır, 24 saat içinde hâkim onayı alınır. Tanıklıktan çekinebilecek kişilerle iletişim kayda alınamaz.', tip:'Tanıklıktan çekinebilecek yakınların iletişimi dinlenemez! Sınavda çok sorulan istisna.'},
      {num:'m.147', title:'Sorguda Bilgilendirme Zorunluluğu', body:'İfade öncesi şüpheli/sanığa okunması zorunlulular: yüklenen suç, susma hakkı, müdafi seçme hakkı, lehte delil toplama hakkı. Bu bildirim yapılmadan alınan beyan geçersizdir.', tip:'Haklar bildirilmeden alınan ifade mahkemede kullanılamaz.'},
      {num:'m.160', title:'Savcının Görevi', body:'Savcı suç haberi alır almaz gerçeği araştırır; hem aleyhte hem lehte delil toplar. Kamu davasını açmaya yer olup olmadığına karar verir.', tip:'Savcı yalnızca aleyhte değil, lehte delil de toplar. Tarafsız kamu makamıdır.'},
      {num:'m.206', title:'Delil Yasakları', body:'Hukuka aykırı yollarla elde edilen deliller reddedilir; devlet sırrı ve tanıklık ayrıcalığı kapsamındaki bilgiler delil olamaz.', tip:'"Zehirli ağacın meyvesi" doktrini: Hukuka aykırı delilden elde edilen delil de kullanılamaz.'},
      {num:'m.253', title:'Uzlaştırma', body:'Yalnızca kanunda sayılan katalog suçlara uygulanır. Tarafların anlaşmasıyla soruşturma veya kovuşturma sona erer. Uzlaşma sağlanamazsa yargılama normal seyrinde devam eder.', tip:'Tüm suçlara değil, katalog suçlara uygulanır. Soruşturma ve kovuşturma aşamasında mümkündür.'},
      {num:'m.272–273', title:'İstinaf', body:'İlk derece mahkemesi kararlarına karşı Bölge Adliye Mahkemesi\'ne başvurulur. Başvuru süresi tebliğden itibaren 15 gündür. Hem maddi hem hukuki inceleme yapılır.', tip:'İstinaf süresi: 15 gün (tebliğden). İstinaf = maddi + hukuki inceleme.'},
      {num:'m.288–289', title:'Temyiz', body:'İstinaf kararlarına karşı Yargıtay\'a başvurulur. Yalnızca hukuka aykırılık gerekçesiyle temyiz yapılabilir; maddi vakıalar temyiz sebebi olamaz. Başvuru süresi 15 gündür.', tip:'Temyiz süresi: 15 gün. Yalnızca hukuki denetim; maddi olaylara karışamaz.'},
      {num:'m.2 (suçüstü/toplu)', title:'Suçüstü Hâli ve Toplu Suç', body:'Suçüstü: (1) İşlenmekte olan suç, (2) Henüz işlenmiş fiil ile fiilin hemen ardından takip edilerek yakalanan kişi, (3) Fiilin pek az önce işlendiğini gösteren eşya/delille yakalanan kişi. Toplu suç: Aralarında iştirak iradesi olmasa bile 3 veya daha fazla kişi tarafından işlenen suçtur.', tip:'Toplu suçta eşik: 3+ kişi (2 kişi yetmez). Suçüstü üç farklı durumu kapsar.'},
      {num:'m.12–18', title:'Yetkili Mahkeme', body:'Kural: Suçun işlendiği yer mahkemesi. Teşebbüste: son icra hareketinin yapıldığı yer. Zincirleme suçta: son suçun işlendiği yer. Suçun işlendiği yer belli değilse: yakalandığı yer, yoksa yerleşim yeri. Diplomatik dokunulmazlıktan yararlanan kamu görevlileri için: Ankara mahkemesi.', tip:'Yetkisizlik itirazı sanığın sorgusundan önce yapılmalıdır; sonradan ileri sürülemez.'},
      {num:'m.39', title:'Sürelerin Hesaplanması', body:'Gün ile belirlenen süre: tebliğin ertesi günü başlar. Haftalık süre: aynı gün adına karşılık gelen haftanın son günü mesai bitiminde sona erer. Son gün tatile rastlarsa: tatili izleyen ilk iş günü biter.', tip:'"Tebliğ günü sayılmaz, ertesi gün başlar." Son gün tatilse uzar.'},
      {num:'m.45–46', title:'Tanıklıktan Çekinme', body:'M.45 – Kişisel sebeple çekinme: şüpheli/sanığın nişanlısı, eşi (evlilik bitse de), usul-füru kan/kayın hısımları (3. derece dahil kan, 2. derece dahil kayın), evlatlık bağı olanlar, 15 yaş altı ve ayırt etme gücü olmayanlar. M.46 – Meslek sebebiyle: avukat, hekim, noter ve yardımcıları sır kapsamındaki bilgiler için çekinebilir.', tip:'Çekinme hakkı sadece belirtilen kişilere tanınır. Dinlenmeden önce hak bildirilmek zorundadır.'},
      {num:'m.50–55', title:'Yemin ve Yeminsiz Tanıklar', body:'Yeminsiz dinlenecekler: (1) 15 yaşını doldurmamış olanlar, (2) Ayırt etme gücü olmayanlar, (3) Suça iştirak edenler veya suçluyu kayıranlar. Yemin biçimi: "Bildiğimi dosdoğru söyleyeceğim, namusum ve vicdanım üzerine yemin ederim." Yemin sırasında herkes ayağa kalkar.', tip:'15 yaş altı = yeminsiz. Yemin bozulursa yalan tanıklık suçu oluşur.'},
      {num:'m.74', title:'Gözlem Altına Alınma', body:'Akıl hastalığı şüphesiyle resmi sağlık kurumunda gözlem: Soruşturma evresinde Sulh Ceza Hâkimi, kovuşturma evresinde mahkeme karar verir. Süre: her seferinde 3 haftayı geçemez; toplamda 3 ayı aşamaz. Karara itiraz edilebilir.', tip:'Soruşturma = Sulh Ceza Hâkimi. Kovuşturma = Mahkeme. Toplam max 3 ay.'},
      {num:'m.75', title:'Beden Muayenesi', body:'İç beden muayenesi ve vücuttan örnek (kan, DNA, tırnak, saç) alma: hâkim/mahkeme kararı şart; acilde savcı karar verir (24 saat içinde hâkime sunar). Üst sınırı 2 yıldan az hapis cezasını gerektiren suçlarda bu işlemler yapılamaz.', tip:'2 yıldan az suç = muayene ve örnek alma yasak. Savcı kararı 24 saat içinde hâkime gitmeli.'},
      {num:'m.79', title:'Moleküler Genetik İnceleme', body:'DNA analizi ve soybağı tespiti için alınan örnekler üzerinde yapılan inceleme: yalnızca hâkim karar verebilir (savcı ve mahkeme değil). Sonuçlar kişisel veri niteliğindedir; başka amaçla kullanılamaz. İnceleme sonuçları beraat/CYOY kararı kesinleşince imha edilir.', tip:'Genetik inceleme = SADECE hâkim kararı. Savcı da, mahkeme de tek başına karar veremez.'},
      {num:'m.87', title:'Otopsi', body:'Otopsi: Savcı huzurunda, biri adli tıp veya patoloji uzmanı olmak üzere iki hekim tarafından yapılır. Otopsi zorunlu olarak baş, göğüs ve karın açılmasını gerektirir. Gömülü cesedi çıkarma: soruşturmada savcı, kovuşturmada mahkeme karar verir.', tip:'2 hekim (birisi adli tıp/patoloji). Baş + Göğüs + Karın = üç bölge açılmalı. Gömülü için ayrı karar gerekir.'},
      {num:'m.135 (süre)', title:'İletişim Denetlenmesi Süreleri', body:'Tedbir süresi: En çok 2 ay; 1 ay daha uzatılabilir (toplam 3 ay). Örgüt suçlarında: ek olarak her defasında 1 ayı aşmamak ve toplam 3 ayı geçmemek üzere uzatılabilir. Savcının başlattığı tedbir 24 saat içinde hâkim onayına sunulur; hâkim 24 saat içinde karar verir.', tip:'Normal: 2+1 ay. Örgüt: +3 ay daha (toplam 6 ay). 24+24 saat onay süreci kritik.'},
      {num:'m.140', title:'Teknik Araçlarla İzleme', body:'Konut ve işyerinde ses/görüntü kaydı: hâkim kararı (acilde savcı, 24 saat içinde hâkime sunulur). Süre: en çok 3 hafta; 1 hafta daha uzatılabilir. Örgüt suçlarında: her defasında 1 haftayı aşmamak ve toplam 4 haftayı geçmemek üzere uzatma. Gizli soruşturmacı (m.139) ile birlikte uygulanırsa süreler 1 kat artırılır.', tip:'Normal: 3+1 hafta. Örgüt: +4 hafta daha. Gizli soruşturmacı ile birlikte süreler 2 katına çıkar.'},
      {num:'m.141–142', title:'Koruma Tedbiri Tazminatı', body:'Haksız yakalama, tutuklama veya usulsüz işlemler nedeniyle tazminat hakkı doğar. Başvuru: kararın kesinleştiğinin tebliğinden itibaren 3 ay ve her hâlde 1 yıl içinde. Başvuru yeri: zarara uğrayanın oturduğu yer Ağır Ceza Mahkemesi. Tazminat davası yalnızca devlet aleyhine açılabilir.', tip:'3 ay (tebliğden) ve her hâlde 1 yıl. Ağır Ceza Mahkemesi. Devlet aleyhine → devlet ilgiliye rücu eder.'},
      {num:'m.148', title:'İfade/Sorguda Yasak Usüller', body:'Yasak: kötü davranma, işkence, ilaç verme, yorma, aldatma, cebir/tehdit. Yasak yollarla elde edilen ifadeler rıza olsa bile delil olarak kullanılamaz. Müdafi hazır olmaksızın kollukça alınan ifade, hâkim/mahkemede sanık tarafından doğrulanmadıkça hükme esas alınamaz.', tip:'"Kolluk ifadesi tek başına delil değildir" — hâkim önünde onaylanmadan geçersizdir.'},
      {num:'m.149–150', title:'Müdafi Seçimi ve Zorunlu Müdafilik', body:'Şüpheli/sanık soruşturma ve kovuşturmanın her aşamasında müdafi yardımından yararlanabilir. İfade almada en çok 3 avukat hazır bulunabilir. Zorunlu müdafi: çocuk, ağır malul, sağır/dilsiz sanıklarda istem aranmaksızın atanır. Alt sınırı 5 yıldan fazla hapis gerektiren suçlarda da zorunlu müdafi atanır.', tip:'3 avukat sınırı: ifade alma sırasında. Zorunlu atama: çocuk + malul + sağır/dilsiz + 5 yıldan fazla suç.'},
      {num:'m.175', title:'İddianamenin Kabulü ve Kovuşturma', body:'İddianamenin kabulüyle kamu davası açılmış olur ve kovuşturma evresi başlar. Sanığa iddianame + çağrı kağıdı birlikte tebliğ edilir. Çağrı kağıdı ile duruşma günü arasında en az 1 hafta bulunmalıdır.', tip:'İddianame kabulü = kovuşturmanın başlangıcı. Soruşturma: şüpheli → Kovuşturma: sanık. 1 hafta asgari süre.'},
      {num:'m.231', title:'Hükmün Açıklanmasının Geri Bırakılması (HAGB)', body:'Şartlar: (1) 2 yıl veya daha az hapis cezası, (2) Daha önce kasıtlı suçtan mahkûmiyet yok, (3) Zararın giderilmesi, (4) Tekrar suç işlemeyeceğine kanaat, (5) Sanığın kabul etmesi. Denetim süresi: 5 yıl. Sürede yeni kasıtlı suç işlenmezse dava düşer; işlenirse hüküm açıklanır.', tip:'5 şart + 5 yıl denetim. Sanık kabul etmezse HAGB verilemez. Karar itirazla denetlenir.'},
      {num:'m.251', title:'Basit Yargılama Usulü', body:'Asliye Ceza Mahkemesinde; adli para cezası veya üst sınırı 2 yıl veya daha az hapis cezasını gerektiren suçlarda uygulanır. Duruşma yapılmaksızın karar verilir. Mahkûmiyet hâlinde sonuç ceza 1/4 oranında indirilir. Yaş küçüklüğü ve akıl hastalığı hâllerinde uygulanmaz.', tip:'Üst sınır 2 yıl. 1/4 indirim. Duruşmasız. Çocuk ve akıl hastasına uygulanmaz.'},
    ]
  },
  pvsk: {
    name:'Polis Vazife ve Salahiyet K. (PVSK)', short:'PVSK',
    articles:[
      {num:'m.2', title:'Polisin Genel Görevleri', body:'Polis; suç işlenmesini önlemek, kamu düzenini ve güvenliği korumak, suçluları yakalamak ve adli makamlara teslim etmekle görevlidir. Hem önleyici (idari) hem adli kolluk görevini üstlenir.', tip:'Önleyici kolluk = suç öncesi. Adli kolluk = suç sonrası. Aynı personel her ikisini de yapar.'},
      {num:'m.4/A', title:'Durdurma ve Kimlik Sorma', body:'Makul şüphe bulunan hâllerde kişi ve araç durdurulabilir, kimlik sorulabilir. Durdurma süresi en fazla 30 dakika; kimlik tespiti amacıyla götürmede azami süre 4 saattir.', tip:'Makul şüphe = somut + nesnel veriler. Durdurma: 30 dk. Kimlik tespiti (götürmede): 4 saat.'},
      {num:'m.9', title:'Önleme Araması', body:'Suç işleneceğine ilişkin makul şüphe varsa mülki amirin yazılı emriyle kişi ve araçlar aranabilir. Hâkim kararı gerekmez; idari nitelikli bir aramadır.', tip:'Önleme araması = idari (mülki amir emri). Adli arama = suç şüphesiyle hâkim/savcı kararı.'},
      {num:'m.13', title:'Zor Kullanma Yetkisi', body:'Direnç veya saldırıyla karşılaşıldığında orantılı biçimde zor kullanılabilir. Kademeler: (1) beden gücü → (2) maddi araçlar (kelepçe, cop, tazyikli su/gaz) → (3) silah.', tip:'Kademeli zor: beden gücü → maddi araç → silah. Hepsinde orantılılık zorunludur.'},
      {num:'m.16', title:'Silah Kullanma Yetkisi', body:'Silah kullanmadan önce: (1) Dur emri, (2) Uyarı ateşi, (3) Etkisiz kılmaya yönelik ateş. Meşru müdafaa, ağır suçlu yakalamak veya toplu şiddeti bastırmak gibi hâllerde uygulanır.', tip:'Zorunlu sıra: Dur emri → Uyarı ateşi → Etkisiz kılmaya ateş. Sıra atlanamaz.'},
      {num:'m.17', title:'Yakalama Yetkisi', body:'Suçüstü hâlinde veya kaçmakta olan kişiyi polis gözaltına alabilir. Gözaltı derhâl Cumhuriyet Savcısına bildirilir.', tip:'Gözaltına alma anında savcılığa bildirim zorunludur.'},
      {num:'m.19', title:'Gözaltı', body:'Suç şüphesi altındaki kişi 24 saate kadar gözaltında tutulabilir. Toplu suçlarda savcı emriyle uzatılabilir (CMK m.91 ile uyumlu). Gözaltı = Tutuklama değildir; tutuklama hâkim kararı gerektirir.', tip:'Gözaltı (polis) ≠ Tutuklama (hâkim). Gözaltı makul şüpheyle yeterli; tutuklama kuvvetli şüphe gerektirir.'},
    ]
  },
  pvsk2: {
    name:'Emniyet Teşkilat Kanunu (ETK)', short:'ETK',
    articles:[
      {num:'m.1–2', title:'Teşkilatın Yapısı ve Bağlılığı', body:'Emniyet Genel Müdürlüğü İçişleri Bakanlığı\'na bağlıdır. Merkez (EGM) ve taşra (il/ilçe emniyet müdürlükleri) teşkilatından oluşur. Ülkenin genel güvenlik işlerinden İçişleri Bakanı sorumludur.', tip:'EGM → İçişleri Bakanlığı. Taşra hiyerarşisi: İl → İlçe.'},
      {num:'m.3', title:'Polisin Tanımı ve Görevleri', body:'Polis; asayişi, kamu düzenini, şahıs ve mal güvenliğini korumakla, suçluları takip ve yakalamakla görevli silahlı devlet kuvvetidir.', tip:'Silahlı devlet kuvveti. Sivil polis de bu tanım kapsamındadır.'},
      {num:'m.13', title:'Rütbe Sistemi', body:'Polis memuru rütbe sırası (küçükten büyüğe): Polis Memuru → Kıdemli Polis Memuru → Komiser Yardımcısı → Komiser → Başkomiser → Emniyet Amiri → Emniyet Müdürü (4.→3.→2.→1. Sınıf) → Sınıf Üstü Emniyet Müdürü.', tip:'PAEM Komiser Yardımcısı yetiştirmek için açılır; rütbe sıralaması sıklıkla sorulur.'},
      {num:'m.14', title:'Terfi ve Atama', body:'Terfi; kıdem, başarı değerlendirmesi ve sınav başarısı koşuluna bağlıdır. Emniyet Müdürlüğü kadrolarına atama İçişleri Bakanının teklifi ve Cumhurbaşkanı onayıyla yapılır.', tip:'Terfi otomatik değildir: kıdem + sınav başarısı birlikte şarttır.'},
      {num:'m.47', title:'Disiplin Cezaları', body:'Uyarma, kınama, aylıktan kesme, kademe ilerlemesinin durdurulması ve meslekten ihraç olmak üzere 5 disiplin yaptırımı vardır. Meslekten ihraç en ağır yaptırım olup Danıştay denetimine tabidir.', tip:'5 disiplin cezası. Meslekten ihraç → Danıştay denetiminde.'},
    ]
  },
  iyuk: {
    name:'İdari Yargılama Usulü K. (İYUK)', short:'İYUK',
    articles:[
      {num:'m.2', title:'İdari Dava Türleri', body:'İdare mahkemelerinde üç tür dava açılabilir: (1) İptal davası (hukuka aykırı işlemin kaldırılması), (2) Tam yargı davası (tazminat), (3) İdari sözleşmelerden doğan davalar.', tip:'İptal = işlemi ortadan kaldır. Tam yargı = zarar tazminat. İkisi aynı davada birlikte istenebilir.'},
      {num:'m.7', title:'Dava Açma Süreleri', body:'İdare ve Danıştay\'da dava açma süresi tebliğden itibaren 60 gündür. Vergi mahkemelerinde 30 gün. İvedi yargılama usulünde (m.20/A) 30 gün.', tip:'İdare mahkemesi = 60 gün · Vergi mahkemesi = 30 gün · İvedi = 30 gün. Hepsi tebliğden.'},
      {num:'m.10', title:'İdari Makama Başvuru', body:'İlgililer, dava konusu edilebilecek işlem veya eylemin yapılması için önce idari makama başvurabilir. 60 gün içinde cevap verilmezse istek reddedilmiş sayılır; dava açma süresi işlemeye başlar.', tip:'İdare 60 gün susarsa red sayılır. Bu tarihten itibaren 60 günlük dava açma süresi başlar.'},
      {num:'m.20', title:'İdari Yargı Denetiminin Sınırı', body:'İdare mahkemeleri idari eylem ve işlemlerin yalnızca hukuka uygunluğunu denetler; yerindelik denetimi yapamaz. Bu sınır hukuk devleti ilkesinin gereğidir.', tip:'Hukuka uygunluk denetimi yapılır; yerindelik (faydalı mı?) denetimi yapılmaz.'},
      {num:'m.27', title:'Yürütmenin Durdurulması', body:'İki şart birlikte aranır: (1) İdari işlemin açıkça hukuka aykırı olması + (2) Uygulanması hâlinde telafisi güç ya da imkânsız zararın doğacağı. Davalı idare savunması alınmadan karar verilemez.', tip:'İKİ ŞART birlikte zorunlu: Açık hukuka aykırılık + Telafi edilemez zarar.'},
      {num:'m.46', title:'Temyiz', body:'Bölge idare mahkemesi kararları ve belirli Danıştay ilk derece kararlarına karşı Danıştay\'a temyiz yoluna başvurulabilir. Temyiz süresi tebliğden itibaren 30 gündür.', tip:'İdari yargıda temyiz süresi: 30 gün. Temyiz mercii: Danıştay.'},
      {num:'m.50', title:'Karar Düzeltme', body:'Danıştay kararlarına karşı 15 gün içinde karar düzeltme yoluna gidilebilir. Yalnızca kanunda sayılan sınırlı gerekçelerle başvurulabilen olağanüstü bir kanun yoludur.', tip:'Karar düzeltme süresi: 15 gün. Olağanüstü yol; sınırlı gerekçelerle açılabilir.'},
    ]
  },
  aihm: {
    name:'Avrupa İnsan Hakları Sözleşmesi (AİHS)', short:'AİHS',
    articles:[
      {num:'m.2', title:'Yaşam Hakkı', body:'Herkesin yaşam hakkı yasayla korunur. Mutlak değildir; meşru müdafaa, kaçmanın önlenmesi veya ayaklanmanın bastırılması gibi istisnalar öngörülmüştür (m.2/2). Türkiye ölüm cezasını 2002\'de kaldırmıştır.', tip:'Mutlak DEĞİL; m.2/2 istisnalar var. m.3 (işkence) ise kesinlikle mutlaktır.'},
      {num:'m.3', title:'İşkence Yasağı', body:'Hiç kimse işkenceye, insanlık dışı ya da aşağılayıcı muameleye tabi tutulamaz. MUTLAK bir haktır; savaş veya olağanüstü hal dahil hiçbir koşulda askıya alınamaz.', tip:'MUTLAK HAK — Psikolojik baskı, aşırı sorgu yöntemleri de bu madde kapsamındadır.'},
      {num:'m.4', title:'Kölelik ve Zorla Çalıştırma Yasağı', body:'Hiç kimse kölelik veya esaret altında tutulamaz; zorunlu çalıştırılamaz. Kölelik yasağı mutlaktır. Askerlik, mahkûm çalıştırma ve sivil yükümlülük zorunlu çalışma sayılmaz.', tip:'Kölelik yasağı = MUTLAK. Askerlik/mahkûm/zorunlu hizmet istisnadır.'},
      {num:'m.5', title:'Özgürlük ve Güvenlik Hakkı', body:'Yasada öngörülen istisnalar dışında kimse özgürlüğünden yoksun bırakılamaz. Tutuklanan kişi hâkim önüne çıkarılma hakkına sahiptir. Sınırlandırılabilen bir haktır.', tip:'Sınırlandırılabilen hak. Keyfi tutuklama yasaktır. Tutuklanan neden tutulduğunu hemen öğrenmelidir.'},
      {num:'m.6', title:'Adil Yargılanma Hakkı', body:'Bağımsız ve tarafsız bir mahkemede makul sürede, açık yargılama hakkı. Masumiyet karinesi, savunma hakkı, tanık sorgulama ve tercüman hakkını kapsar. Hem cezai hem medeni davalarda geçerlidir.', tip:'Unsurlar: Bağımsız mahkeme + Makul süre + Aleniyet + Masumiyet karinesi + Savunma hakkı.'},
      {num:'m.7', title:'Kanunsuz Ceza Olmaz', body:'Suç tarihinde ulusal veya uluslararası hukukta suç sayılmayan eylem nedeniyle kimse mahkûm edilemez. MUTLAK bir haktır; olağanüstü hâllerde bile askıya alınamaz.', tip:'MUTLAK HAK. TCK m.2 ile örtüşür. Savaşta dahi geçerlidir.'},
      {num:'m.8', title:'Özel ve Aile Hayatına Saygı', body:'Özel hayat, aile hayatı, konut ve yazışma gizliliği güvence altındadır. Sınırlandırılabilen bir haktır; ulusal güvenlik veya suç önleme gibi meşru amaçlarla kanuni dayanak gerektirir.', tip:'Mutlak DEĞİL. Üç şart: Kanuni dayanak + Meşru amaç + Demokratik toplumda zorunluluk.'},
      {num:'m.9–11', title:'Temel Özgürlükler', body:'m.9: Düşünce, vicdan ve din özgürlüğü. m.10: İfade özgürlüğü (basın dahil). m.11: Toplanma ve dernek kurma özgürlüğü. Üçü de sınırlandırılabilen haklardır.', tip:'Üçü de sınırlandırılabilir. Türkiye aleyhine en çok ihlal kararı: m.10 (ifade özgürlüğü).'},
      {num:'m.13', title:'Etkili Başvuru Hakkı', body:'AİHS\'te tanınan bir hakkın ihlal edilmesi durumunda ulusal makam önünde etkili başvuru hakkı güvence altındadır. Türkiye\'de AYM bireysel başvuru bu amaçla oluşturulmuştur.', tip:'Önce iç hukuk yolları tüketilmeli; ardından AİHM başvurusu mümkün.'},
      {num:'m.34–35', title:'Bireysel Başvuru ve Kabul Koşulları', body:'Gerçek/tüzel kişiler ve STK\'lar AİHM\'e bireysel başvuruda bulunabilir. Koşullar: (1) İç hukuk yollarının tüketilmesi + (2) Son karardan itibaren 4 ay içinde başvuru (2022\'den önce 6 ay idi).', tip:'Başvuru süresi 4 ay (2022 değişikliğiyle 6 aydan indirildi). İç yollar tüketilmeden başvurulamaz.'},
    ]
  },
  kab: {
    name:'Kabahatler Kanunu (5326)', short:'Kabahatler',
    articles:[
      {num:'m.2–3', title:'Kabahat Tanımı ve Kanunîlik', body:'Kabahat: Kanunda açıkça düzenlenmiş, hukuka aykırı ve karşılığı idari yaptırım olan fiil. Suçtan farkı: Kabahat yaptırımı idari para cezası veya müsaderedir; hapis cezası uygulanmaz. Kast veya taksirle işlenebilir; kanun taksirle işlenebileceğini açıkça belirtmemişse kast aranır.', tip:'Kabahat → idari yaptırım (hapis yok). Taksir ancak kanun açıkça öngörürse.'},
      {num:'m.16–17', title:'İdari Yaptırım Türleri ve Karar Mercii', body:'Yaptırım türleri: (1) İdari para cezası, (2) Mülkiyet müsaderesi. Karar mercii: Kanunda belirtilen yetkili makam (vali, belediye başkanı vb.). Suçüstü halinde kolluk da idari para cezasına karar verebilir. İdari para cezasına itiraz: Sulh Ceza Hâkimliğine 15 gün içinde yapılır.', tip:'Kolluk karar yetkisi yalnızca suçüstü halinde. İtiraz: sulh ceza hâkimliği, 15 gün.'},
      {num:'m.20', title:'Zamanaşımı', body:'Kabahat için zamanaşımı süresi 3 yıldır. Süre fiilin işlendiği tarihten itibaren işler. Zamanaşımı dolduğunda yaptırım kararı verilemez; verilmişse infaz edilemez. Suç ve kabahat bir arada bulunduğunda ayrı ayrı zamanaşımı uygulanır.', tip:'3 yıl zamanaşımı. Suç-kabahat birlikteliğinde zamanaşımı bağımsız işler.'},
      {num:'m.14–15', title:'İştirak ve Teşebbüs', body:'İştirak: Birden fazla kişinin kabahati birlikte işlemesi halinde her biri hakkında ayrı ayrı yaptırım uygulanır. Teşebbüs: Kabahat teşebbüs aşamasında kaldığında tamamlanmış kabahate göre daha az ceza uygulanır (2/3\'ü). Not: Suçtaki teşebbüsten farklı olarak kabahatte cezasızlık değil indirim uygulanır.', tip:'İştirak → herkes ayrı ceza. Teşebbüs → 2/3 indirim (suçtan farklı: cezasızlık yok).'},
      {num:'m.22–23', title:'Birden Fazla Kabahat ve Sorumluluk', body:'Aynı eylem hem kabahat hem suç oluşturuyorsa sadece suç hükümleri uygulanır; kabahat yaptırımı uygulanmaz. Tüzel kişiye ait işletmelerde kabahati işleyen gerçek kişi cezalandırılır; tüzel kişi hakkında ihtiyari olarak "güvenlik tedbiri" (faaliyet durdurma, izin iptali) uygulanabilir.', tip:'Suç + kabahat birlikte → sadece suç cezalandırılır. Tüzel kişi: güvenlik tedbiri (ihtiyari).'},
    ]
  },
  tmk: {
    name:'Terörle Mücadele Kanunu (3713)', short:'TMK',
    articles:[
      {num:'m.1', title:'Terör Tanımı', body:'Anayasal düzeni, devlet bütünlüğünü veya hükümeti zor, şiddet, baskı, korkutma ya da tehdit yöntemleriyle değiştirmeye yönelik eylemleri gerçekleştiren örgüt veya kişilerin faaliyetleri terördür. Yalnız kişi de terör suçu işleyebilir.', tip:'Örgüt şart değil; tek kişi de terör faili olabilir. Amaç + Şiddet yöntemi esastır.'},
      {num:'m.3–7', title:'Terör Suçları ve Cezalar', body:'Terör örgütü kuran/yöneten: 10–15 yıl hapis. Üye olan: 5–10 yıl hapis. Terör örgütü propagandası (m.7/2): 1–5 yıl hapis. Terör suçlarında ceza alt sınırından indirilemez ve ertelemeler uygulanmaz.', tip:'Yönetici 10–15 · Üye 5–10 · Propaganda 1–5. İndirim yasağı dikkat çekicidir.'},
      {num:'m.10', title:'Gözaltı ve Yargılama', body:'Terör suçlarında gözaltı: savcı kararıyla 4 güne kadar uzatılabilir; hâkim kararıyla 7 güne kadar. Karar yetkisi: Sulh Ceza Hâkimi değil, Ağır Ceza Mahkemesi nöbetçi hâkimi. Terör suçları adli tatilde de görülür.', tip:'Normal gözaltı: 4 gün (savcı). Hâkim kararıyla: 7 gün. Hâkim: Ağır Ceza nöbetçisi.'},
      {num:'m.5–6', title:'Terör Örgütü Adına Suç İşleme ve Silahlı Örgüt', body:'Örgüt üyesi olmaksızın terör örgütü adına suç işleyen kişi hem ilgili suçtan hem de örgüt üyeliğinden ayrıca cezalandırılır (m.5). Silahlı terör örgütüne katılmak, bu örgüt adına propaganda yapmak veya yardım etmek bağımsız suç sayılır (m.6). Alt ve üst sınırdan indirim yapılamaz.', tip:'Örgüt üyesi olmadan bile suç işlese → üyelik cezası da. m.5-6 indirim yasağı.'},
      {num:'m.14', title:'Gizlilik ve Yayın Yasağı', body:'Soruşturma ve kovuşturma aşamasında terör suçlarına ilişkin bilgi ve belgelerin yayınlanması yasaktır. Yasağa aykırı yayın yapanlar hakkında 1–3 yıl hapis cezası öngörülmüştür. Mahkeme, delil karartma veya sanık güvenliği gerekçesiyle duruşmaların gizli yapılmasına karar verebilir.', tip:'Yayın yasağı. İhlal: 1–3 yıl. Duruşma gizli yapılabilir.'},
    ]
  },
  aile: {
    name:'Ailenin Korunması Kanunu (6284)', short:'6284',
    articles:[
      {num:'m.3–5', title:'Koruyucu ve Önleyici Tedbirler', body:'Koruyucu tedbir: Şiddet mağduruna yönelik (barınma, geçici nafaka, psikolojik destek). Aile mahkemesi hâkimi veya acil hallerde mülki amir verebilir. Önleyici tedbir: Şiddet uygulayana yönelik (uzaklaştırma, iletişim yasağı, silah teslimi). Yalnızca aile mahkemesi hâkimi tarafından verilir.', tip:'Koruyucu = mağdura (hâkim veya mülki amir). Önleyici = faile (YALNIZCA hâkim).'},
      {num:'m.8', title:'Tedbir Süresi ve İhlal Yaptırımı', body:'Tedbirler en fazla 6 ay süreyle verilebilir; zorunluluk halinde uzatılabilir. Tedbir kararına aykırı davranış halinde: 3–10 gün zorlama hapsi uygulanır. Tekrar halinde hapis süresi artırılır. Zorlama hapsi adli sicile işlenmez.', tip:'6 ay sınırı. İhlal → 3–10 gün zorlama hapsi (adli sicile işlenmez).'},
      {num:'m.12', title:'ŞÖNİM ve Destek Hizmetleri', body:'Şiddet Önleme ve İzleme Merkezi (ŞÖNİM): İl bazında kurulur; tedbir kararlarının uygulanmasını izler, mağdura ücretsiz destek sağlar. Acil yardım hattı: 183. Kuruluş sorumluluğu: Aile ve Sosyal Hizmetler Bakanlığı.', tip:'183 = ŞÖNİM hattı. ŞÖNİM ücretsiz; kurumdan faydalanmak için şikâyet şart değil.'},
      {num:'m.6–7', title:'Kolluğun Görev ve Yetkileri', body:'Kolluğun acil hali: Gecikmesinde sakınca bulunan hallerde kolluk, geçici tedbir kararı alarak şiddet failini konuttan uzaklaştırabilir ve derhal hâkime bildirir. 48 saat içinde hâkim onayı alınmazsa tedbir kendiliğinden kalkar. Delil tespiti: Kolluk, şiddet izlerini fotoğraflama, tıbbi rapor talep etme yetkisine sahiptir.', tip:'Kolluk acil uzaklaştırma: 48 saat + hâkim onayı. Onay gelmezse tedbir kalkar.'},
      {num:'m.17', title:'Suçüstü ve Tutuklama', body:'6284 kapsamındaki suçüstü hallerinde savcılık kanalı beklenmeksizin gözaltı yapılabilir. Tedbir kararına bilerek aykırı davranan kişi hakkında CMK hükümleri çerçevesinde tutuklama kararı da verilebilir. Bu suçlar için şikâyetten vazgeçme kovuşturmayı etkilemez (kamu davası niteliğindedir).', tip:'Şikâyetten vazgeçme: kovuşturma durmuyor (kamu davası). Suçüstü → doğrudan gözaltı.'},
    ]
  },
  kacak: {
    name:'Kaçakçılıkla Mücadele Kanunu (5607)', short:'5607',
    articles:[
      {num:'m.3', title:'Temel Kaçakçılık Suçları', body:'Gümrük denetimini atlatarak mal ithali/ihracı: 1–5 yıl hapis + adli para cezası. Nitelikli haller (örgütle, silahla, resmi belge sahteciliğiyle): ceza 1/2 oranında artırılır. Suça teşebbüs de tam suç gibi cezalandırılır.', tip:'Örgütlü kaçakçılık: +1/2 artırım. Teşebbüs = tamamlanmış gibi ceza.'},
      {num:'m.4', title:'Akaryakıt ve Tütün Kaçakçılığı', body:'Akaryakıt kaçakçılığı (bant uygulamasını ihlal dahil): 2–5 yıl hapis. Tütün mamulleri kaçakçılığı: 2–5 yıl hapis. Kaçakçılık konusu malı satmak, bulundurmak veya nakletmek de suç kapsamındadır.', tip:'Akaryakıt ve sigara: 2–5 yıl. Satmak ve bulundurmak da suç sayılır.'},
      {num:'m.13', title:'Müsadere', body:'Kaçakçılık konusu eşyanın müsaderesi zorunludur (hâkim takdir yetkisi yoktur). Nakilde kullanılan araç: örgütlü kaçakçılıkta zorunlu müsadere, bireysel kaçakçılıkta ihtiyari müsadere.', tip:'Eşya müsaderesi zorunlu. Araç: örgütlüyse zorunlu, değilse ihtiyari.'},
      {num:'m.10–11', title:'Etkin Pişmanlık', body:'Suç ortaklarını yetkili makamlara bildiren veya ele geçirilmelerine yardımcı olan kişiler hakkında ceza indirimi uygulanır (1/3 ila 2/3). Örgütün faaliyetlerini ortaya çıkaran kişi cezasızlık hükmünden yararlanabilir. Etkin pişmanlık kovuşturma başlamadan bildirilirse daha geniş indirim sağlar.', tip:'Etkin pişmanlık: 1/3–2/3 indirim. Örgütü ifşa etme → cezasızlık mümkün.'},
      {num:'m.16', title:'İdari El Koyma ve Gümrük İdaresinin Yetkisi', body:'Gümrük idaresi, kaçakçılık şüphesiyle eşyaya re\'sen el koyabilir; 24 saat içinde sulh ceza hâkiminin onayına sunulur. El konulan eşya bozulabilir nitelikteyse mahkeme kararı beklenmeksizin derhal değerlendirilebilir (satış, imha). İstatistik görevlerini yerine getirmeyen ithalatçılar da yaptırıma tabidir.', tip:'Gümrük → el koyma → 24 saat hâkim onayı. Bozulabilir eşya → derhal değerlendirme.'},
    ]
  },
  trafik: {
    name:'Karayolları Trafik Kanunu (2918)', short:'KTK',
    articles:[
      {num:'m.2–3', title:'Temel Tanımlar', body:'Karayolu: Trafik için kamunun yararlanmasına açık arazi şeridi. Araç: Karayolunda kullanılan her türlü taşıt. Trafik kazası: Karayolunda hareket halindeyken meydana gelen, yaralanma, ölüm veya maddi hasara yol açan olay.', tip:'Trafik kazası: Karayolu + hareket hâli + sonuç (yaralanma/ölüm/hasar). Üçü birlikte aranır.'},
      {num:'m.48', title:'Alkol ve Uyuşturucu Sınırları', body:'Hafif taşıt sürücüleri: 0,50 promil alkol sınırı. Ticari araç/kamu taşıtı sürücüleri: 0,20 promil. 0,50–1,00 arası: idari para cezası + sürücü belgesi geçici iptali. 1,00 promil üzeri: TCK m.179 kapsamında suç (trafik güvenliğini tehlikeye atma).', tip:'Hafif taşıt: 0,50. Ticari: 0,20. 1,00+ → TCK suçu. Promil barajları sıklıkla sorulur.'},
      {num:'m.65–68', title:'Ehliyet ve Tescil', body:'Sürücü belgesi olmadan araç kullanmak yasaktır; ceza: idari para + araç trafikten men. Araç satışında tescil devri: 30 gün içinde yapılmalıdır. Trafik tescil işlemleri İçişleri Bakanlığı\'na bağlı trafik birimlerince yürütülür.', tip:'Tescil devri: 30 gün. Ehliyet olmadan araç = trafik cezası + men.'},
      {num:'m.51–54', title:'Kaza Anında Yükümlülükler', body:'Kaza yapan araç sürücüsü: (1) Durmalı, (2) Yardım çağırmalı, (3) Güvenli alan oluşturmalı, (4) Yetkililere bildirim yapmalı. Maddi hasarlı kazalarda tutanak düzenlenir; anlaşmazlıkta trafik polis/jandarması çağrılır. Kaza yerini terk etmek: TCK kapsamında ayrı suç. Ölümlü/yaralamalı kazada kaza yeri değiştirilemez.', tip:'Kaza yeri terki: TCK suçu. Ölümlü/yaralamalı: kaza yeri değiştirilemez.'},
      {num:'m.84', title:'Trafik Cezasına İtiraz', body:'Trafik idari para cezalarına itiraz: Sulh Ceza Hâkimliğine 15 gün içinde yapılır. Trafikten men kararları da 15 gün içinde itiraz konusu yapılabilir. Elektronik denetleme cihazlarıyla (EDS/HGS) tespit edilen cezalara itiraz: cezanın tebliğinden itibaren 15 gün. Hâkimlik itirazı kesin karara bağlar.', tip:'İtiraz: 15 gün. Makam: Sulh Ceza Hâkimliği. EDS/HGS cezaları da dahil.'},
    ]
  },
  tanik: {
    name:'Tanık Koruma Kanunu (5726)', short:'5726',
    articles:[
      {num:'m.3', title:'Koruma Tedbirleri', body:'Tanık ve yakınlarına uygulanabilecek tedbirler (hafiften ağıra): (1) Kimlik ve adres bilgilerinin gizlenmesi, (2) Kılık değişikliği, (3) Korunan konut, (4) Çalışma yeri değişikliği, (5) Kimlik değişikliği. Tanık ifadesini ses/görüntü bağlantısıyla da verebilir.', tip:'5 tedbir kademesi. Kimlik değişikliği en ağır. İfade görüntülü bağlantıyla verilebilir.'},
      {num:'m.4', title:'Koruma Kararı', body:'Koruma kararı: Cumhuriyet savcısının talebi ve hâkimin onayıyla ağır ceza mahkemesi bünyesindeki koruma kurulu tarafından verilir. Korunan tanığın kimliği sanığa, müdafiine ve hatta dosyaya bile gizli tutulabilir.', tip:'Savcı talebi + hâkim onayı. Kimlik sanığa bile gizli tutulabilir.'},
      {num:'m.9', title:'Yükümlülük ve İhlal', body:'Koruma altındaki tanık kurallara uymak zorundadır (adres bildirme, güvenlik talimatları). İhlal halinde koruma kararı kaldırılabilir ve sağlanan maddi destekler geri istenebilir.', tip:'Tanık da yükümlü. İhlal → koruma kalkar + maddi destek iade.'},
      {num:'m.5', title:'Kimlik Değişikliği', body:'En ağır koruma tedbiri: Kimlik değişikliği kararı yalnızca ağır ceza mahkemesi nöbetçi hâkimi tarafından verilir. Yeni kimlik belgesi, pasaport, nüfus cüzdanı ve sicil kaydı oluşturulur; eski kimlikle bağlantı izleri silinir. Kimlik değişikliği sonrası önceki bilgilerin ifşa edilmesi suç sayılır.', tip:'Kimlik değişikliği: Ağır Ceza Hâkimi. Önceki bilgileri ifşa etmek suçtur.'},
      {num:'m.7–8', title:'Mali Destek ve Gizlilik Yükümlülüğü', body:'Koruma altındaki tanığa zorunlu harcamalar karşılanmak üzere devlet tarafından mali destek sağlanabilir. Bu destekler karara bağlanırken tanığın mali durumu gözetilir. Koruma programına dâhil olan tüm kamu görevlileri, tanığın kimlik bilgilerini gizli tutmakla yükümlüdür; ifşa edenlere hapis cezası öngörülmüştür.', tip:'Mali destek: devlet karşılar. Gizlilik: tüm kamu görevlileri yükümlü.'},
    ]
  },
  pasaport: {
    name:'Pasaport Kanunu (5682)', short:'5682',
    articles:[
      {num:'m.1–2', title:'Pasaport Zorunluluğu', body:'TC vatandaşları yurt dışına çıkmak için pasaport veya pasaport yerine geçen belge taşımak zorundadır. Pasaport TC adına İçişleri Bakanlığı\'nca düzenlenir; yurt dışında konsolosluklarca verilebilir.', tip:'Pasaport verir: İçişleri Bakanlığı (yurt dışında: konsolosluk).'},
      {num:'m.14', title:'Pasaport Çeşitleri', body:'(1) Umuma mahsus pasaport (bordo/kırmızı): Tüm vatandaşlara. (2) Hususi pasaport (gri): Kamu görevlileri ve ailelerine. (3) Hizmet pasaportu (yeşil): Kamu hizmetiyle yurt dışına gidenlere. (4) Diplomatik pasaport (siyah): Diplomatik göreve atananlara. Geçici pasaport: Acil çıkışlarda 3 ay geçerli.', tip:'Renk sırası: Bordo=umuma · Gri=hususi · Yeşil=hizmet · Siyah=diplomatik.'},
      {num:'m.22', title:'Pasaport Verilmeyecek ve Çıkış Yasaklı Haller', body:'Pasaport verilmez: Tutuklu/hükümlüler. Borç nedeniyle çıkış yasağı: yalnızca mahkeme kararıyla. Devlet sırrına vakıf kişiler: Cumhurbaşkanı kararıyla çıkışları kısıtlanabilir. Sahte pasaport: TCK kapsamında suç.', tip:'Tutuklu/hükümlü → pasaport yok (kendiliğinden). Borçlu → mahkeme kararı gerekir.'},
      {num:'m.6', title:'Pasaport Süresi ve Yenileme', body:'Umuma mahsus pasaport geçerlilik süresi 10 yıldır (18 yaş altı: 5 yıl). Hususi pasaport (gri): kamu görevinde bulunulan süreyle sınırlı, en fazla 5 yıl. Diplomatik pasaport: görev süresince geçerli. Pasaport kaybolduğunda en yakın kolluğa/konsolosluğa bildirim zorunludur; kayıp bildirimi yapılmadan alınan pasaport iptal edilir.', tip:'Umuma mahsus: 10 yıl (çocuk: 5 yıl). Hususi: en fazla 5 yıl. Kayıp bildirim zorunlu.'},
      {num:'m.4', title:'Çıkış İzninde Özel Haller', body:'18 yaş altı çocukların yurt dışına çıkışı: Velayet hakkı bulunan anne/babanın veya mahkemenin iznini gerektirir. Tek başına çıkışta noterce düzenlenmiş muvafakatname gerekebilir. Yargılama devam ederken yurt dışına çıkış: mahkemenin yazılı iznine bağlıdır. Tahliye olan hükümlü: hükümlülük süresince pasaport verilmesi kısıtlanabilir.', tip:'Çocuk yurt dışı: velayet + muvafakatname. Yargılama devam ederken: mahkeme izni.'},
    ]
  },
  kvkk: {
    name:'Kişisel Verilerin Korunması Kanunu (6698)', short:'KVKK',
    articles:[
      {num:'m.3–4', title:'Tanımlar ve İşleme İlkeleri', body:'Kişisel veri: Kimliği belirli/belirlenebilir gerçek kişiye ilişkin her türlü bilgi. Özel nitelikli: ırk, siyasi görüş, din, sağlık, cinsel hayat, ceza mahkûmiyeti vb. 5 işleme ilkesi: Hukuka uygunluk, doğruluk, belirli amaçla sınırlılık, asgari veri, saklama sınırlılığı.', tip:'5 ilke ezberlemeli. Özel nitelikli veri daha katı koruma altında.'},
      {num:'m.5–6', title:'Veri İşleme Koşulları', body:'Normal veri işleme: Açık rıza VEYA kanunda öngörülmüş haller (sözleşme, hukuki yükümlülük, meşru menfaat vb.). Özel nitelikli veri: Kural olarak açık rıza şart. Sağlık/cinsel hayat verisi: Yalnızca sağlık personelince ve koruyucu hizmetlerde işlenebilir.', tip:'Normal veri: rıza veya kanun. Sağlık/cinsel veri: YALNIZCA sağlık personeli.'},
      {num:'m.11 + m.20', title:'İlgili Kişi Hakları ve KVK Kurulu', body:'Veri sahibinin 7 hakkı: Öğrenme, bilgi alma, düzeltme, silme/imha, bildirme, itiraz, tazminat. Yanıt süresi: 30 gün. KVK Kurulu: 9 üye (5\'i TBMM, 4\'ü Cumhurbaşkanınca seçilir). Veri ihlali bildirimi: 72 saat içinde Kurula.', tip:'7 hak · 30 gün yanıt · 9 üye kurul · 72 saat ihlal bildirimi — dördü sıklıkla sorulur.'},
      {num:'m.7', title:'Silme, İmha ve Anonim Hale Getirme', body:'Kişisel veriler: İşleme amacı ortadan kalktığında, veri sahibinin talebi üzerine veya kanunda öngörülen saklama süresinin dolmasıyla silinmeli, imha edilmeli ya da anonim hale getirilmelidir. Periyodik imha: en geç 6 ayda bir yapılır. Anonim veri: kimliği belirlenemeyen hale gelen veri artık KVKK kapsamı dışına çıkar.', tip:'Periyodik imha: 6 ayda bir. Anonim veri → KVKK kapsamı dışına çıkar.'},
      {num:'m.12', title:'Veri Güvenliği Yükümlülükleri', body:'Veri sorumlusu, teknik ve idari tedbirleri almakla yükümlüdür: Şifreleme, erişim yetkilendirme, sızma testi, çalışan eğitimi, imha politikası. İhlal durumunda 72 saat içinde KVK Kuruluna bildirim yapılır; mağdurlara da bildirim yapılmalıdır. Yükümlülükleri ihlal eden veri sorumlularına idari para cezası: 40.000–1.000.000 TL bandında.', tip:'Teknik + idari tedbirler. İhlal → 72 saat KVK bildirimi + mağdur bildirimi. Para cezası: 40K–1M TL.'},
    ]
  },
  kimlik: {
    name:'Kimlik Bildirme Kanunu (1774)', short:'1774',
    articles:[
      {num:'m.1–2', title:'Kimlik Bildirme Yükümlülüğü', body:'Otel, motel, pansiyon, apart otel, tatil köyü, kamping gibi konaklama işletmeleri; misafir girişinden itibaren 24 saat içinde kimlik bilgilerini yetkili güvenlik birimine bildirmek zorundadır. Hem Türk hem yabancı misafirler bildirim kapsamındadır.', tip:'24 saat içinde bildirim. Yabancı misafirler için ek önem taşır.'},
      {num:'m.3–4', title:'Bildirim İçeriği ve Kayıt', body:'Bildirilen bilgiler: ad-soyad, kimlik/pasaport numarası, doğum tarihi, uyruk, giriş-çıkış tarihi. Kayıtlar en az 5 yıl muhafaza edilir. Elektronik bildirim sistemi (GÖÇ-NET) üzerinden de bildirim yapılabilir.', tip:'Kayıt saklama: 5 yıl. GÖÇ-NET elektronik sistem.'},
      {num:'m.6', title:'Yaptırım ve Denetim', body:'Yükümlülüğü yerine getirmeyen işletme sahipleri idari para cezasıyla cezalandırılır. Yabancı misafir bildiriminin yapılmaması ek yaptırıma yol açabilir. Denetim yetkisi emniyet ve jandarma birimlerine aittir.', tip:'Yaptırım: idari para cezası. Denetim: emniyet + jandarma.'},
      {num:'m.5', title:'Yabancı Uyruklu Bildirimi', body:'Yabancı uyruklu misafirlerin bildirimi konsolosluk ve büyükelçiliklere ek olarak İl Göç İdaresi Müdürlüğüne de iletilir. Vizesiz giriş yapabilen uyruklar ile Türkiye\'de ikamet izni bulunan yabancılar aynı bildirime tabidir. Yabancının kayıt dışı konaklatılması; hem 1774 hem de 6458 sayılı Yabancılar Kanunu kapsamında yaptırıma yol açar.', tip:'Yabancı: Göç İdaresi + konsolosluk bildirimi. 6458 de devreye girer.'},
      {num:'m.7–8', title:'İşletme Açma ve Kapama Bildirimi', body:'Konaklama işletmeleri; açılıştan önce yetkili emniyet/jandarma birimine kayıt yaptırmak zorundadır. İşletme unvanı veya sahibinin değişmesi durumunda 15 gün içinde güncelleme bildirimi yapılmalıdır. Geçici süre faaliyetin durdurulması halinde de ilgili birime bildirim zorunludur; bildirimden muaf tutulan işletmeler yoktur.', tip:'Açılış öncesi kayıt zorunlu. Unvan/sahip değişikliği: 15 gün içinde bildir.'},
    ]
  },
  dmk: {
    name:'Devlet Memurları Kanunu (657)', short:'657',
    articles:[
      {num:'m.48', title:'Memurluğa Giriş Şartları', body:'TC vatandaşı olmak, 18 yaşını tamamlamış olmak, en az ortaöğretim mezunu olmak, kamu haklarından mahrum bulunmamak, taksirli suçlar hariç 1 yıldan fazla hapis ya da devlet aleyhine/terör suçundan mahkûm olmamak, akıl hastalığı bulunmamak.', tip:'"1 yıldan fazla" ve "taksirli hariç" ifadeleri kritik. 6 temel şart.'},
      {num:'m.125', title:'Disiplin Cezaları', body:'5 kademeli disiplin cezası (hafiften ağıra): (1) Uyarma, (2) Kınama, (3) Aylıktan kesme (1/30–1/8), (4) Kademe ilerlemesinin durdurulması (1–3 yıl), (5) Devlet memurluğundan çıkarma. Çıkarma kararı Yüksek Disiplin Kurulu tarafından verilir.', tip:'5 ceza. Meslekten çıkarma → Yüksek Disiplin Kurulu. Aylıktan kesme: 1/30–1/8.'},
      {num:'m.177', title:'İzin Hakları', body:'Yıllık izin: 1–10 yıl kıdeme kadar 20 gün; 10 yılı aşanlar için 30 gün. Mazeret izni: evlilik, ölüm, doğum olaylarında 7 güne kadar. Memurlar greve katılamaz, siyasi partiye üye olamaz.', tip:'Yıllık izin: <10 yıl=20gün · 10yıl+=30gün. Grev ve siyasi parti yasak.'},
      {num:'m.7–11', title:'Memurların Temel Yükümlülükleri', body:'Tarafsızlık ve liyakat: Kamu hizmeti tarafsız ve eşit sunulmalıdır (m.7). Sadakat: Anayasal düzene ve devlete bağlılık (m.8). Davranış kuralları: Halka nazik, saygılı, yardımcı davranma zorunluluğu (m.9). Mal bildirimi: Göreve başlayışta ve her yıl (m.10). Kamuoyuna açıklama yasağı: İzinsiz basın açıklaması yapmak disiplin suçu (m.11).', tip:'5 temel yükümlülük: Tarafsızlık, sadakat, davranış, mal bildirimi, açıklama yasağı.'},
      {num:'m.36', title:'Sınıflandırma ve Kariyer Grupları', body:'657 kapsamındaki personel 10 hizmet sınıfına ayrılır: GİH (Genel İdare Hizmetleri), EÖH (Eğitim-Öğretim), SH (Sağlık), TH (Teknik), AH (Avukatlık), MH (Mülki İdare), TZH (Din Hizmetleri), YH (Yardımcı Hizmetler), EH (Emniyet), MİT. Kariyer meslekler (hâkim, noter, müfettiş vb.) 657\'ye değil özel statü kanunlarına tabidir.', tip:'10 hizmet sınıfı. Emniyet Hizmetleri Sınıfı (EH) = polis. Kariyer meslek → özel kanun.'},
    ]
  },
  vatandaslik: {
    name:'Türk Vatandaşlığı Kanunu (5901)', short:'TVK',
    articles:[
      {num:'m.6–7', title:'Doğumla Vatandaşlık Kazanımı', body:'Soy bağına göre (neseple): TC vatandaşı anne veya babanın çocuğu doğumla Türk vatandaşıdır — birincil ilke. Doğum yerine göre (ius soli): Türkiye\'de doğan ve başka devlet vatandaşlığı kazanamayan kişi Türk vatandaşı sayılır — tamamlayıcı ilke.', tip:'Soy bağı = birincil. Doğum yeri = tamamlayıcı. Anne veya babadan biri yeterli.'},
      {num:'m.11–16', title:'Sonradan Vatandaşlık Kazanımı', body:'Yetkili makam kararıyla: 5 yıl kesintisiz Türkiye\'de ikamet + medeni hal yeterliliği + suç kaydı olmaması. Evlenmeyle: TC vatandaşıyla 3 yıl evli kalmak + birlikte yaşamak + başvuru. Yatırım yoluyla da vatandaşlık verilebilir (Cumhurbaşkanı kararıyla).', tip:'Normal: 5 yıl ikamet. Evlilikle: 3 yıl evlilik + birlikte yaşama. İkisi farklı!'},
      {num:'m.25–27', title:'Vatandaşlıktan Çıkma ve Çıkarılma', body:'Çıkma: İçişleri Bakanlığı iznine tabidir; askerlik yükümlülüğü olanlar erteleme talep edebilir. Çıkarılma: TC ile bağdaşmayan yabancı devlet hizmetine girme, Türkiye aleyhine eylem gibi hallerde Cumhurbaşkanı kararıyla. Vatansızlık durumu yaratılmaması gözetilir.', tip:'Çıkma: gönüllü + İçişleri izni. Çıkarılma: Cumhurbaşkanı kararı. Vatansızlık yaratılmaz.'},
      {num:'m.34–37', title:'Çift Vatandaşlık ve Kısıtlamalar', body:'Türkiye çift vatandaşlığa izin verir; yabancı vatandaşlık kazanılması Türk vatandaşlığını sona erdirmez. Ancak bazı kamu görevleri (askerlik, seçim, hâkimlik) sadece Türk vatandaşlarına açıktır — çift vatandaşlar bu hakları Türk kimliğiyle kullanabilir. Yabancı ülkenin çıkar çatışmasına giren ordusuna katılmak vatandaşlıktan çıkarma sebebidir.', tip:'Çift vatandaşlık serbest. Kamu görevi hakkı: Türk vatandaşlığı üzerinden. Yabancı ordu → çıkarılma.'},
      {num:'m.44–45', title:'Vatandaşlık Belgesi ve Kimlik Tespiti', body:'Nüfus cüzdanı ve pasaport Türk vatandaşlığının temel belgeleridir; resmi işlemlerde kimlik tespitinde kullanılır. Nüfus kayıtları Nüfus Müdürlüklerince tutulur; kayıplar mahkeme kararıyla tescil edilir. Vatandaşlık tespiti için İçişleri Bakanlığı nezdinde uyuşmazlık çözüm mekanizması işletilir; karara itiraz idare mahkemesinde yapılır.', tip:'Kimlik belgesi: nüfus cüzdanı + pasaport. Kayıp tescil: mahkeme kararı. İtiraz: idare mahkemesi.'},
    ]
  },
  resmiyas: {
    name:'Resmî Yazışma Yönetmeliği', short:'Resmi Yazışma',
    articles:[
      {num:'Yazı Türleri', title:'Resmî Yazı Türleri', body:'Yazı: Kurum içi/kurumlar arası resmi iletişim belgesi. Onay: Makam içi onay belgesi. Olur: Üst makamdan alınan yazılı izin. Genelge: Genel uygulamayı bildiren talimat. Yönerge: Teknik uygulama kılavuzu. Tutanak: Toplantı veya olayı belgeleyen belge.', tip:'Onay ≠ Olur: Onay = makam içi; Olur = üst makamdan izin. Yönerge ≠ Yönetmelik.'},
      {num:'Bölümler', title:'Resmî Yazının Zorunlu Bölümleri', body:'8 zorunlu bölüm: (1) Başlık (kurum adı + amblem), (2) Sayı ve tarih (sol üst), (3) Konu, (4) Gönderilen makam (Sayın…), (5) Metin, (6) İmza (ad-soyad-unvan), (7) Ekler, (8) Dağıtım. İmzanın altında ad soyad büyük harfle, unvan küçük harfle yazılır.', tip:'8 bölüm. İmza altında: AD SOYAD büyük, unvan küçük harf.'},
      {num:'Paraf ve İmza', title:'Paraf, İmza Devri ve Tarih', body:'Paraf: Yetkili imzadan önce hazırlayan/inceleyen kişilerin koyduğu onay işareti. İmza yetkisi devri: Yazılı yetki devri belgesiyle yapılır; devredilemeyen yetkiler (savcıya yazı, mahkemeye bildirim vb.) bu kapsama girmez. Yazı tarihi ile imza tarihi aynı olmalıdır.', tip:'Paraf = hazırlayan onayı. Devredilemeyen yetkiler var. Yazı tarihi = imza tarihi.'},
      {num:'Gizlilik', title:'Gizlilik Dereceli Yazılar', body:'Derecelendirme (hafiften ağıra): (1) Hizmete Özel, (2) Gizli, (3) Çok Gizli. Gizli yazılar çift zarfla gönderilir; dış zarfta sadece alıcı adresi, iç zarfta gizlilik derecesi belirtilir. Gizli yazıların kopyalanması, başka kişilere gösterilmesi ve imha edilmeden atılması yasaktır. İmha: belirlenen makamın gözetiminde imza karşılığı yapılır.', tip:'3 derece: Hizmete Özel → Gizli → Çok Gizli. İmha: imza karşılığı + yetkili makam.'},
      {num:'Kayıt ve Arşiv', title:'Kayıt, Sayı Sistemi ve Arşivleme', body:'Gelen yazılar "Gelen Evrak Defteri"ne, giden yazılar "Giden Evrak Defteri"ne kaydedilir. Her yazıya eşsiz kayıt numarası verilir: Birim kodu / Yıl / Sıra no (örn: EGM/2024/001). Arşivleme: yazılar dosyalanarak en az 5 yıl kurumsal arşivde saklanır; imha edilecek belgeler Devlet Arşivleri mevzuatına uygun şekilde ayıklanır.', tip:'Sayı formatı: Birim/Yıl/Sıra. 5 yıl asgari saklama. İmha: Devlet Arşivleri mevzuatı.'},
    ]
  }
};